using System.ComponentModel;
using System.Text;
using Daxter.Core;
using Daxter.Core.Editing;
using Daxter.Core.Maintenance;
using Daxter.Core.Rest;
using Daxter.Core.Scheduling;
using ModelContextProtocol.Server;

namespace Daxter.Cli.Mcp;

/// <summary>
/// MCP tools over the Power BI Service. Most accept optional <c>workspace</c>/<c>dataset</c>
/// arguments (name or id) that override the server's config. Read tools are annotated
/// <c>ReadOnly = true</c>; the two mutating tools (<c>daxter_refresh</c>, <c>daxter_clear_cache</c>)
/// are annotated <c>Destructive = true</c> and stay dry-run unless writes are explicitly enabled.
/// </summary>
[McpServerToolType]
public static class DaxterTools
{
    [McpServerTool(Name = "daxter_capabilities", ReadOnly = true, Title = "List all DAXter features/tools"), Description(
        "List EVERY DAXter tool — name, title, whether it reads or writes, and what it does — plus the running version. " +
        "Call this FIRST to discover the full set of features in one shot: query/DAX, metadata, refresh + resume, model " +
        "editing, connections, report export/classification, pipelines, audits, gateways. Always complete and current — " +
        "it is generated by reflecting the registered tools at runtime, so every release automatically surfaces its new " +
        "features here. Use it whenever you're unsure what DAXter can do.")]
    public static string Capabilities() => DaxterToolRuntime.CapabilitiesJson();

    [McpServerTool(Name = "daxter_version", ReadOnly = true, Title = "Show the running DAXter version (+ optional update check)"),
     Description("Return identity info for the DAXter instance the agent is talking to: version stamped at build time, " +
                 "GHCR image tag, GitHub repo URL, .NET runtime, OS / architecture. Pass `checkLatest=true` to ALSO " +
                 "hit GitHub for the latest published release and a `update_available` boolean (one outbound API call, " +
                 "no auth). Cheaper than daxter_capabilities when you only need the version. Use to confirm which build " +
                 "you're on (especially across sessions or shared/hosted DAXters), to feature-gate against capabilities " +
                 "that landed in a specific release, or to suggest an update.")]
    public static Task<string> Version(
        [Description("Check GitHub for the latest published release (one outbound API call). Default false.")] bool checkLatest = false,
        CancellationToken ct = default)
        => DaxterToolRuntime.VersionAsync(checkLatest, ct);

    [McpServerTool(Name = "daxter_login", Title = "Sign in to Power BI (and optionally Fabric SQL)"),
     Description("Sign in interactively (device code). Returns a URL and a code to enter in your browser; once you complete it, the other tools run as you. " +
                 "Call this if a tool reports 'Not signed in'. " +
                 "Pass target=\"sql\" to sign in for Fabric Warehouse / Lakehouse SQL endpoints — that's a SEPARATE one-time sign-in (different pre-authorized client id) because Power BI's first-party client id isn't authorized for database.windows.net (AADSTS65002). " +
                 "(No effect when the server uses a service principal.)")]
    public static Task<string> Login(
        [Description("Sign-in target: \"powerbi\" (default — XMLA + REST) or \"sql\" (Fabric SQL endpoint).")] string? target = null,
        CancellationToken ct = default)
        => DaxterToolRuntime.LoginAsync(ct, target);

    [McpServerTool(Name = "daxter_query", ReadOnly = true, Title = "Run DAX/MDX query"),
     Description("Run a DAX or MDX query against a Power BI semantic model. Returns rows as JSON. " +
                 "AUTO-ATTACHES shared-knowledge context cards under `context/workspaces/{ws}/` and " +
                 "`context/datasets/{ws}/{ds}/` to the response footer — curated glossaries / conventions / " +
                 "client-specific facts arrive WITH the data, no extra call needed. Curate via daxter_context_put.")]
    public static Task<string> Query(
        [Description("The DAX or MDX query, e.g. EVALUATE TOPN(10, Sales)")] string query,
        [Description("Workspace name or id/GUID (optional; defaults to server config)")] string? workspace = null,
        [Description("Dataset / model name or id/GUID (optional; defaults to server config). Pass names with apostrophes as-is.")] string? dataset = null,
        CancellationToken ct = default)
        => DaxterToolRuntime.XmlaAsync(workspace, dataset, s => s.Execute(query), ct, attachContext: true);

    [McpServerTool(Name = "daxter_dmv", ReadOnly = true, Title = "Run DMV query"), Description("Run a DMV ($SYSTEM) query, e.g. SELECT * FROM $SYSTEM.TMSCHEMA_TABLES.")]
    public static Task<string> Dmv(
        [Description("A DMV SELECT statement.")] string statement,
        string? workspace = null, string? dataset = null, CancellationToken ct = default)
        => DaxterToolRuntime.XmlaAsync(workspace, dataset, s => s.Execute(statement), ct);

    [McpServerTool(Name = "daxter_list_tables", ReadOnly = true, Title = "List tables"), Description("List the tables in a semantic model.")]
    public static Task<string> ListTables(string? workspace = null, string? dataset = null, CancellationToken ct = default)
        => DaxterToolRuntime.XmlaAsync(workspace, dataset,
            s => s.Execute("SELECT [Name] AS [Table] FROM $SYSTEM.TMSCHEMA_TABLES ORDER BY [Name]"), ct);

    [McpServerTool(Name = "daxter_measures", ReadOnly = true, Title = "List measures"), Description("List measures in a model. Set withExpression=true to include the DAX.")]
    public static Task<string> Measures(
        [Description("Include each measure's DAX expression.")] bool withExpression = false,
        string? workspace = null, string? dataset = null, CancellationToken ct = default)
        => DaxterToolRuntime.MetaAsync(workspace, dataset, m => m.Measures(withExpression), ct);

    [McpServerTool(Name = "daxter_measure", ReadOnly = true, Title = "Show measure definition"), Description("Show one measure's full definition (name, type, folder, format, DAX).")]
    public static Task<string> Measure(
        [Description("Measure name.")] string name,
        string? workspace = null, string? dataset = null, CancellationToken ct = default)
        => DaxterToolRuntime.MetaAsync(workspace, dataset, m => m.Measure(name), ct);

    [McpServerTool(Name = "daxter_mcode", ReadOnly = true, Title = "Show Power Query (M)"), Description("Show the Power Query (M) code for a table's partitions.")]
    public static Task<string> MCode(
        [Description("Table name.")] string table,
        string? workspace = null, string? dataset = null, CancellationToken ct = default)
        => DaxterToolRuntime.MetaAsync(workspace, dataset, m => m.MCode(table), ct);

    [McpServerTool(Name = "daxter_parameters", ReadOnly = true, Title = "List parameters"), Description("List the model's shared M expressions / parameters.")]
    public static Task<string> Parameters(string? workspace = null, string? dataset = null, CancellationToken ct = default)
        => DaxterToolRuntime.MetaAsync(workspace, dataset, m => m.Parameters(), ct);

    [McpServerTool(Name = "daxter_partitions", ReadOnly = true, Title = "List partitions"), Description("List partitions and last-refresh times, optionally for one table.")]
    public static Task<string> Partitions(
        [Description("Table name (optional; all partitions if omitted).")] string? table = null,
        string? workspace = null, string? dataset = null, CancellationToken ct = default)
        => DaxterToolRuntime.MetaAsync(workspace, dataset, m => m.Partitions(table), ct);

    [McpServerTool(Name = "daxter_columns", ReadOnly = true, Title = "List columns"), Description("List columns in a model (name, data type, hidden), optionally for one table. Excludes the internal RowNumber column.")]
    public static Task<string> Columns(
        [Description("Table name (optional; all columns with their table id if omitted).")] string? table = null,
        string? workspace = null, string? dataset = null, CancellationToken ct = default)
        => DaxterToolRuntime.MetaAsync(workspace, dataset, m => m.Columns(table), ct);

    [McpServerTool(Name = "daxter_rls", ReadOnly = true, Title = "List RLS roles"),
     Description("List RLS roles in a model (name + model permission). " +
                 "Use daxter_role_filters to see the DAX filter expression each role applies per table, " +
                 "and daxter_role_members to see who's in each role.")]
    public static Task<string> Rls(string? workspace = null, string? dataset = null, CancellationToken ct = default)
        => DaxterToolRuntime.MetaAsync(workspace, dataset, m => m.Roles(), ct);

    [McpServerTool(Name = "daxter_role_filters", ReadOnly = true, Title = "Show a role's table filter expressions (DAX)"),
     Description("Show every table-level RLS filter expression defined for a role — the DAX a model author wrote " +
                 "in Tabular Editor / Power BI Desktop under Table Permissions. Returns (Table, FilterExpression) " +
                 "rows; the FilterExpression is the raw DAX (often a CALCULATETABLE/SUMMARIZE/FILTER chain). " +
                 "Tables not listed have no row filter for this role (they're either accessible without restriction " +
                 "for read roles, or implicit by relationship). Pair with daxter_role_members to see who the role " +
                 "filters apply to, and daxter_test_rls to run a query under the role.")]
    public static Task<string> RoleFilters(
        [Description("Role name (from daxter_rls).")] string role,
        string? workspace = null, string? dataset = null, CancellationToken ct = default)
        => DaxterToolRuntime.MetaAsync(workspace, dataset, m => m.RoleFilters(role), ct);

    [McpServerTool(Name = "daxter_role_members", ReadOnly = true, Title = "Show a role's members"),
     Description("Show every member assigned to an RLS role — name (typically a UPN, security group, or app id), " +
                 "member type (User / Group), and identity provider. Note: membership is set per environment " +
                 "(workspace assignment in the Power BI service is also a layer above this); these rows reflect " +
                 "what the model itself declares.")]
    public static Task<string> RoleMembers(
        [Description("Role name (from daxter_rls).")] string role,
        string? workspace = null, string? dataset = null, CancellationToken ct = default)
        => DaxterToolRuntime.MetaAsync(workspace, dataset, m => m.RoleMembers(role), ct);

    [McpServerTool(Name = "daxter_diff_measures", ReadOnly = true, Title = "Compare measures"), Description("Compare measures between the configured model and another model in the same workspace.")]
    public static Task<string> DiffMeasures(
        [Description("The other dataset/model name to compare against.")] string other,
        string? workspace = null, string? dataset = null, CancellationToken ct = default)
        => DaxterToolRuntime.DiffMeasuresAsync(workspace, dataset, other, ct);

    [McpServerTool(Name = "daxter_refresh_history", ReadOnly = true, Title = "Refresh history"), Description("Show recent refresh history (status, start/end) for a model via REST.")]
    public static Task<string> RefreshHistory(
        [Description("Number of recent refreshes (default 10).")] int top = 10,
        string? workspace = null, string? dataset = null, CancellationToken ct = default)
        => DaxterToolRuntime.RestAsync(workspace, dataset, async (rest, cfg, c) =>
        {
            var groupId = await rest.ResolveGroupIdAsync(cfg.Workspace, c);
            var datasetId = await rest.ResolveDatasetIdAsync(groupId, cfg.Dataset!, c);
            return await rest.RefreshHistoryAsync(groupId, datasetId, top, c);
        }, ct);

    [McpServerTool(Name = "daxter_refresh_schedule", ReadOnly = true, Title = "Show scheduled refresh"), Description(
        "Show the Power BI Service 'Scheduled refresh' config for an import model — enabled, time zone, days, " +
        "time slots, failure-email. This is the configured schedule (dataset settings), NOT an on-demand refresh " +
        "or DAXter's own job queue. DirectQuery / Direct Lake / Push models report a hint (separate endpoint).")]
    public static Task<string> RefreshSchedule(string? workspace = null, string? dataset = null, CancellationToken ct = default)
        => DaxterToolRuntime.RestAsync(workspace, dataset, async (rest, cfg, c) =>
        {
            var groupId = await rest.ResolveGroupIdAsync(cfg.Workspace, c);
            var datasetId = await rest.ResolveDatasetIdAsync(groupId, cfg.Dataset!, c);
            return PowerBiRestClient.DescribeSchedule(await rest.GetRefreshScheduleAsync(groupId, datasetId, c));
        }, ct);

    [McpServerTool(Name = "daxter_workspaces", ReadOnly = true, Title = "List workspaces"), Description("List Power BI workspaces (with their group ids) the identity can see. No workspace needs to be configured first.")]
    public static Task<string> Workspaces(CancellationToken ct = default)
        => DaxterToolRuntime.RestTenantAsync((rest, c) => rest.GroupsAsync(c), ct);

    [McpServerTool(Name = "daxter_datasets", ReadOnly = true, Title = "List datasets"), Description("List datasets in a workspace.")]
    public static Task<string> Datasets(string? workspace = null, CancellationToken ct = default)
        => DaxterToolRuntime.RestAsync(workspace, null, async (rest, cfg, c) =>
            await rest.DatasetsAsync(await rest.ResolveGroupIdAsync(cfg.Workspace, c), c), ct);

    [McpServerTool(Name = "daxter_reports", ReadOnly = true, Title = "List reports"), Description("List reports in a workspace.")]
    public static Task<string> Reports(string? workspace = null, CancellationToken ct = default)
        => DaxterToolRuntime.RestAsync(workspace, null, async (rest, cfg, c) =>
            await rest.ReportsAsync(await rest.ResolveGroupIdAsync(cfg.Workspace, c), c), ct);

    // ---- take ownership + gateway binding (service config; XMLA can't do these) ----

    [McpServerTool(Name = "daxter_connections", ReadOnly = true, Title = "List all connections"), Description("List every connection you can access (shareable cloud + on-prem/VNet gateway) via the Fabric API: id, display name, connectivity type, and details. Use to find shareable cloud connections independent of any model.")]
    public static Task<string> Connections(CancellationToken ct = default)
        => DaxterToolRuntime.RestTenantAsync((rest, c) => rest.ConnectionsAsync(c), ct);

    [McpServerTool(Name = "daxter_report_inventory", ReadOnly = true, Title = "Classify reports (thin/thick + downloadable)"), Description("Classify every report in a workspace as thin (decoupled from a shared model), thick (embeds its own model — XMLA-editing that model permanently blocks future .pbix download), or paginated, plus whether it's downloadable as a .pbix (service-authored reports aren't). Use to pick which reports are safe to export for analysis.")]
    public static Task<string> ReportInventory(string? workspace = null, CancellationToken ct = default)
        => DaxterToolRuntime.RestAsync(workspace, null, async (rest, cfg, c) =>
            await rest.ReportInventoryAsync(await rest.ResolveGroupIdAsync(cfg.Workspace, c), c), ct);

    [McpServerTool(Name = "daxter_export_report", ReadOnly = true, Title = "Export a report (definition + .pbix)"), Description("Download a report's artifacts: its PBIR/PBIR-Legacy definition (the JSON carrying every field reference — Table[Column], measures — for column-usage analysis) and/or its .pbix. By DEFAULT both are downloaded. Files are written under the persistent token volume (~/.daxter/exports/<report>/) and the tool returns where they landed; pass 'output_dir' to write elsewhere. PREFERRED: pass 'artifact_key' to ALSO mirror the PBIR parts into the artifact store under that key prefix (and the .pbix at <key>.pbix) — then fetch via daxter_artifact_bundle / _get from any host, no docker cp needed. The artifact-store path is how the Power BI alignment-check skill consumes report definitions. Pass pbix=false for just the definition, or definition=false for just the .pbix. Pass 'part' (e.g. report.json) to also return that definition file's content inline for analysis. .pbix fails for service-authored / XMLA-edited reports — that's reported, the definition still comes through. Reads only.")]
    public static Task<string> ExportReport(
        [Description("Report name or id.")] string report,
        [Description("Download the .pbix binary (default true).")] bool pbix = true,
        [Description("Download the PBIR/legacy definition JSON (default true).")] bool definition = true,
        [Description("Directory to write into (default: ~/.daxter/exports, which persists in the token volume).")] string? output_dir = null,
        [Description("Also return this definition file's content inline (e.g. report.json) for analysis.")] string? part = null,
        [Description("Also mirror PBIR parts and .pbix into the artifact store under this key prefix (e.g. 'alignment/sales-dashboard'). Lets the agent fetch via daxter_artifact_bundle / _get from any host with no docker cp.")] string? artifact_key = null,
        string? workspace = null, CancellationToken ct = default)
        => DaxterToolRuntime.RestTextAsync(workspace, async (rest, cfg, c) =>
        {
            var g = await rest.ResolveGroupIdAsync(cfg.Workspace, c);
            var rid = await rest.ResolveReportIdAsync(g, report, c);
            var dir = string.IsNullOrWhiteSpace(output_dir)
                ? Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.UserProfile), ".daxter", "exports")
                : output_dir;
            var safe = string.Concat(report.Select(ch => Path.GetInvalidFileNameChars().Contains(ch) ? '_' : ch));
            var log = new StringBuilder();
            string? inline = null;

            if (definition || !string.IsNullOrWhiteSpace(part))
            {
                var parts = await rest.ReportDefinitionAsync(g, rid, c);
                if (!string.IsNullOrWhiteSpace(part))
                {
                    var p = parts.FirstOrDefault(x => string.Equals(x.Path, part, StringComparison.OrdinalIgnoreCase));
                    inline = p?.Content ?? $"(part not found: {part}; available: {string.Join(", ", parts.Select(x => x.Path))})";
                }
                if (definition)
                {
                    var baseDir = Path.Combine(dir, safe);
                    foreach (var p in parts)
                    {
                        var dest = Path.Combine(baseDir, p.Path.Replace('/', Path.DirectorySeparatorChar));
                        Directory.CreateDirectory(Path.GetDirectoryName(dest)!);
                        await File.WriteAllTextAsync(dest, p.Content, c);
                    }
                    log.AppendLine($"definition: {parts.Count} part(s) → {baseDir}");

                    // Mirror to the artifact store under the user-chosen key prefix. Stamp the
                    // source tool so the /artifacts page tells the user where it came from. This
                    // is the path Diego's alignment-check skill will consume.
                    if (!string.IsNullOrWhiteSpace(artifact_key))
                    {
                        var meta = new Daxter.Core.Artifacts.ArtifactMeta(SourceTool: "daxter_export_report");
                        foreach (var p in parts)
                        {
                            var key = $"{artifact_key.TrimEnd('/')}/{p.Path}";
                            await DaxterToolRuntime.Artifacts.PutAsync(key,
                                new MemoryStream(System.Text.Encoding.UTF8.GetBytes(p.Content)), meta, c);
                        }
                        log.AppendLine($"definition: also mirrored to artifact prefix '{artifact_key}/' ({parts.Count} files) — fetch via daxter_artifact_bundle.");
                    }
                }
            }
            if (pbix)
            {
                try
                {
                    var bytes = await rest.ExportReportPbixAsync(g, rid, c);
                    Directory.CreateDirectory(dir);
                    var pbixPath = Path.Combine(dir, safe + ".pbix");
                    await File.WriteAllBytesAsync(pbixPath, bytes, c);
                    log.AppendLine($"pbix: {bytes.Length:N0} bytes → {pbixPath}");

                    // Same artifact-store mirror for the .pbix. Lands as <artifact_key>.pbix so
                    // it sits alongside the PBIR parts under the same logical prefix.
                    if (!string.IsNullOrWhiteSpace(artifact_key))
                    {
                        var key = $"{artifact_key.TrimEnd('/')}.pbix";
                        await DaxterToolRuntime.Artifacts.PutAsync(key, new MemoryStream(bytes),
                            new Daxter.Core.Artifacts.ArtifactMeta(SourceTool: "daxter_export_report"), c);
                        log.AppendLine($"pbix: also mirrored to artifact '{key}'.");
                    }
                }
                catch (Exception ex)
                {
                    log.AppendLine($"pbix: NOT downloaded — {ex.Message} (service-authored or XMLA-edited reports can't be exported as .pbix).");
                }
            }
            if (inline is not null) { log.AppendLine().AppendLine($"--- {part} ---").AppendLine(inline); }
            return log.Length == 0 ? "Nothing requested — set definition=true and/or pbix=true." : log.ToString();
        }, ct);

    [McpServerTool(Name = "daxter_item_connections", ReadOnly = true, Title = "List a model's connections"), Description("A model's current connections via the Fabric API: display name + connectivity type (cloud / on-prem / VNet gateway) + connection details. Works with model read/write (no gateway-admin), so it names bindings to gateways you can't manage.")]
    public static Task<string> ItemConnections(string? workspace = null, string? dataset = null, CancellationToken ct = default)
        => DaxterToolRuntime.RestAsync(workspace, dataset, async (rest, cfg, c) =>
        {
            var g = await rest.ResolveGroupIdAsync(cfg.Workspace, c);
            var d = await rest.ResolveDatasetIdAsync(g, cfg.Dataset!, c);
            return await rest.ItemConnectionsAsync(g, d, c);
        }, ct);

    [McpServerTool(Name = "daxter_discover_gateways", ReadOnly = true, Title = "Discover bindable gateways"), Description("List the gateways a model can be bound to (those with matching data sources), via REST.")]
    public static Task<string> DiscoverGateways(string? workspace = null, string? dataset = null, CancellationToken ct = default)
        => DaxterToolRuntime.RestAsync(workspace, dataset, async (rest, cfg, c) =>
        {
            var g = await rest.ResolveGroupIdAsync(cfg.Workspace, c);
            var d = await rest.ResolveDatasetIdAsync(g, cfg.Dataset!, c);
            return await rest.DiscoverGatewaysAsync(g, d, c);
        }, ct);

    [McpServerTool(Name = "daxter_gateway_datasources", ReadOnly = true, Title = "List a gateway's data sources"), Description("List the data sources (connections) on a gateway; their ids are what daxter_bind_to_gateway maps to.")]
    public static Task<string> GatewayDatasources(
        [Description("Gateway id (GUID) — from daxter_discover_gateways.")] string gatewayId, CancellationToken ct = default)
        => DaxterToolRuntime.RestTenantAsync((rest, c) => rest.GatewayDatasourcesAsync(gatewayId, c), ct);

    [McpServerTool(Name = "daxter_take_over", Destructive = true, Title = "Take over a model"), Description(
        "Take over ownership of a semantic model (the 'owner left' flow) — required before rebinding its gateway or credentials. " +
        "DRY-RUN by default; set execute=true AND enable writes (web console Configure → Allow writes, or DAXTER_MCP_ALLOW_WRITES=true) to apply. " +
        "Refused on PROD targets when DAXTER_MCP_BLOCK_PROD_WRITES=true.")]
    public static Task<string> TakeOver(
        [Description("Actually take over (default false = dry run).")] bool execute = false,
        string? workspace = null, string? dataset = null, CancellationToken ct = default)
        => DaxterToolRuntime.TakeOverAsync(workspace, dataset, execute, ct);

    [McpServerTool(Name = "daxter_bind_connection", Destructive = true, Title = "Bind a data source to a connection"), Description(
        "Bind a SINGLE semantic-model data source to a connection (Fabric Bind Semantic Model Connection API). Supports ALL " +
        "connectivity types: ShareableCloud (the cloud 'Maps to'), OnPremisesGateway, VirtualNetworkGateway, PersonalCloud, " +
        "Automatic (default SSO), or None (unbind). This SUPERSEDES daxter_bind_to_gateway — it's per-source and can set cloud " +
        "mappings the gateway API can't. Identify the source by its type + path (from daxter_item_connections); pass the target " +
        "connection's id (from daxter_connections) for ShareableCloud/gateway types, or omit it for Automatic/None. You must OWN " +
        "the model (daxter_take_over first). DRY-RUN unless execute=true AND writes enabled. PROD-blockable.")]
    public static Task<string> BindConnection(
        [Description("Data source type, e.g. SQL | Snowflake | Web (the 'type' from daxter_item_connections).")] string sourceType,
        [Description("Data source path identifying WHICH source, e.g. 'server;database' (the 'path' from daxter_item_connections).")] string sourcePath,
        [Description("Connectivity type: ShareableCloud | OnPremisesGateway | VirtualNetworkGateway | PersonalCloud | Automatic | None.")] string connectivityType,
        [Description("Target connection id (GUID) — from daxter_connections. Required for ShareableCloud/gateway; omit for Automatic/None.")] string? connectionId = null,
        [Description("Actually apply (default false = dry run).")] bool execute = false,
        string? workspace = null, string? dataset = null, CancellationToken ct = default)
        => DaxterToolRuntime.BindConnectionAsync(workspace, dataset, connectionId, connectivityType, sourceType, sourcePath, execute, ct);

    [McpServerTool(Name = "daxter_bind_to_gateway", Destructive = true, Title = "Bind a model to a gateway"), Description(
        "Bind a whole semantic model to ONE gateway (legacy Power BI BindToGateway), optionally mapping its sources to specific " +
        "gateway connection ids (comma-separated 'datasourceIds'; omit to bind the first matching data source per source). " +
        "Supports on-premises and VNet gateways. PREFER daxter_bind_connection — it's per-source and also does cloud 'Maps to'. " +
        "DRY-RUN by default; set execute=true AND enable writes to apply. PROD-blockable.")]
    public static Task<string> BindToGateway(
        [Description("Gateway id (GUID) to bind to — from daxter_discover_gateways.")] string gatewayId,
        [Description("Comma-separated gateway data-source/connection ids to map (optional; from daxter_gateway_datasources).")] string? datasourceIds = null,
        [Description("Actually bind (default false = dry run).")] bool execute = false,
        string? workspace = null, string? dataset = null, CancellationToken ct = default)
    {
        var ids = string.IsNullOrWhiteSpace(datasourceIds)
            ? null
            : datasourceIds.Split(',', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries);
        return DaxterToolRuntime.BindToGatewayAsync(workspace, dataset, gatewayId, ids, execute, ct);
    }

    [McpServerTool(Name = "daxter_lineage", ReadOnly = true, Title = "Report to dataset lineage"), Description("Report → dataset lineage for a workspace.")]
    public static Task<string> Lineage(string? workspace = null, CancellationToken ct = default)
        => DaxterToolRuntime.RestAsync(workspace, null, async (rest, cfg, c) =>
            await rest.LineageAsync(await rest.ResolveGroupIdAsync(cfg.Workspace, c), c), ct);

    [McpServerTool(Name = "daxter_export", ReadOnly = true, Title = "Export model (.bim)"), Description("Export the model's full definition as Tabular (.bim) JSON. Large output is truncated — use the CLI for the complete file.")]
    public static Task<string> Export(string? workspace = null, string? dataset = null, CancellationToken ct = default)
        => DaxterToolRuntime.ExportAsync(workspace, dataset, ct);

    [McpServerTool(Name = "daxter_permissions", ReadOnly = true, Title = "List permissions"), Description("Who has access. With a dataset → dataset users; without a dataset → workspace users.")]
    public static Task<string> Permissions(string? dataset = null, string? workspace = null, CancellationToken ct = default)
        => DaxterToolRuntime.RestAsync(workspace, dataset, async (rest, cfg, c) =>
        {
            var groupId = await rest.ResolveGroupIdAsync(cfg.Workspace, c);
            if (!string.IsNullOrWhiteSpace(cfg.Dataset))
            {
                var datasetId = await rest.ResolveDatasetIdAsync(groupId, cfg.Dataset!, c);
                return await rest.DatasetUsersAsync(groupId, datasetId, c);
            }

            return await rest.WorkspaceUsersAsync(groupId, c);
        }, ct);

    [McpServerTool(Name = "daxter_gateways", ReadOnly = true, Title = "List gateways"), Description("List gateways visible to the identity (requires gateway-admin rights).")]
    public static Task<string> Gateways(CancellationToken ct = default)
        => DaxterToolRuntime.RestTenantAsync((rest, c) => rest.GatewaysAsync(c), ct);

    [McpServerTool(Name = "daxter_datasources", ReadOnly = true, Title = "List data sources"), Description("Data sources and gateway binding used by a dataset's refresh.")]
    public static Task<string> Datasources(string? dataset = null, string? workspace = null, CancellationToken ct = default)
        => DaxterToolRuntime.RestAsync(workspace, dataset, async (rest, cfg, c) =>
        {
            var groupId = await rest.ResolveGroupIdAsync(cfg.Workspace, c);
            var datasetId = await rest.ResolveDatasetIdAsync(
                groupId, cfg.Dataset ?? throw new DaxterException("A dataset is required."), c);
            return await rest.DatasourcesAsync(groupId, datasetId, c);
        }, ct);

    [McpServerTool(Name = "daxter_test_rls", ReadOnly = true, Title = "Test RLS"), Description("Test RLS: run a DAX query impersonating a user and/or under a role; returns the filtered result.")]
    public static Task<string> TestRls(
        [Description("DAX query to evaluate under the identity, e.g. EVALUATE ROW(\"n\", COUNTROWS('Sales'))")] string query,
        [Description("RLS role name.")] string? role = null,
        [Description("User UPN to impersonate, e.g. user@contoso.com")] string? user = null,
        string? workspace = null, string? dataset = null, CancellationToken ct = default)
        => DaxterToolRuntime.TestRlsAsync(workspace, dataset, role, user, query, ct);

    [McpServerTool(Name = "daxter_pipelines", ReadOnly = true, Title = "List pipelines"), Description("List Fabric / Power BI deployment pipelines.")]
    public static Task<string> Pipelines(CancellationToken ct = default)
        => DaxterToolRuntime.RestTenantAsync((rest, c) => rest.PipelinesAsync(c), ct);

    [McpServerTool(Name = "daxter_pipeline_stages", ReadOnly = true, Title = "Pipeline stages"), Description("A deployment pipeline's stages (dev/test/prod) and their workspaces.")]
    public static Task<string> PipelineStages(
        [Description("Pipeline id (from daxter_pipelines).")] string pipelineId, CancellationToken ct = default)
        => DaxterToolRuntime.RestTenantAsync((rest, c) => rest.PipelineStagesAsync(pipelineId, c), ct);

    [McpServerTool(Name = "daxter_pipeline_operations", ReadOnly = true, Title = "Pipeline operations"), Description("Recent deploy operations for a pipeline.")]
    public static Task<string> PipelineOperations(
        [Description("Pipeline id (from daxter_pipelines).")] string pipelineId, CancellationToken ct = default)
        => DaxterToolRuntime.RestTenantAsync((rest, c) => rest.PipelineOperationsAsync(pipelineId, c), ct);

    [McpServerTool(Name = "daxter_pipeline_rules", ReadOnly = true, Title = "Pipeline deployment rules"), Description(
        "Deployment-rule check: a model's parameter values across each pipeline stage, flagging where they differ. " +
        "The public Power BI REST API can't read deployment rules directly, so DAXter reads the model's parameters in " +
        "each stage's workspace over XMLA and treats a per-stage value difference as a deployment rule (or manual override). " +
        "Returns columns: Parameter, <stage workspaces…>, RuleApplied.")]
    public static Task<string> PipelineRules(
        [Description("Pipeline id (from daxter_pipelines).")] string pipelineId,
        [Description("Model (semantic dataset) name — same in every stage.")] string model,
        CancellationToken ct = default)
        => DaxterToolRuntime.PipelineRulesAsync(pipelineId, model, ct);

    [McpServerTool(Name = "daxter_pipeline_models_without_rules", ReadOnly = true, Title = "Models without rules"), Description(
        "Pipeline-wide audit: lists models in a pipeline whose parameter values are identical across every stage " +
        "— i.e. no deployment rule (and no manual override) is in effect. Scans every model's parameters in every " +
        "stage via XMLA; potentially slow on large pipelines.")]
    public static Task<string> PipelineModelsWithoutRules(
        [Description("Pipeline id (from daxter_pipelines).")] string pipelineId,
        CancellationToken ct = default)
        => DaxterToolRuntime.PipelineModelsWithoutRulesAsync(pipelineId, ct);

    [McpServerTool(Name = "daxter_pipeline_param_check", ReadOnly = true, Title = "Pipeline parameter check"), Description(
        "Pipeline-wide audit: lists every model whose <param> in <stage> equals (or, with notEquals=true, does not equal) " +
        "<value>. Useful for verifying a deployment rule is consistently applied across all models in an environment " +
        "(e.g. WAREHOUSE_URL in 'Prod' = a fixed endpoint). Scans every model's parameters in every stage via XMLA.")]
    public static Task<string> PipelineParamCheck(
        [Description("Pipeline id (from daxter_pipelines).")] string pipelineId,
        [Description("Stage workspace name (e.g. 'Prod').")] string stage,
        [Description("Parameter name (e.g. DATABASE_NAME).")] string param,
        [Description("Expected value to match against.")] string value,
        [Description("When true, find models whose value does NOT equal the expected.")] bool notEquals = false,
        [Description("Optional: a single model (e.g. 'Sales') — checks just that model and reports its actual value + pass/fail. Omit to scan all models.")] string? model = null,
        CancellationToken ct = default)
        => DaxterToolRuntime.PipelineParamCheckAsync(pipelineId, stage, param, value, notEquals, model, ct);

    [McpServerTool(Name = "daxter_audit_list_saved", ReadOnly = true, Title = "List saved audit checks"), Description(
        "List the named audit checks saved from the web console (shared via ~/.daxter). " +
        "Columns: Name, Pipeline, Stage, Param, Expected. Run one with daxter_audit_run_saved.")]
    public static Task<string> AuditListSaved(CancellationToken ct = default)
        => DaxterToolRuntime.AuditListSavedAsync(ct);

    [McpServerTool(Name = "daxter_audit_run_saved", ReadOnly = true, Title = "Run saved audit check"), Description(
        "Run a saved audit check by its name (as shown by daxter_audit_list_saved) — re-runs the " +
        "stored parameter-value check against its pipeline and returns the matching models.")]
    public static Task<string> AuditRunSaved(
        [Description("Saved check name (case-insensitive).")] string name,
        CancellationToken ct = default)
        => DaxterToolRuntime.AuditRunSavedAsync(name, ct);

    [McpServerTool(Name = "daxter_audit_run_all_saved", ReadOnly = true, Title = "Run all saved audit checks"), Description(
        "Run every saved rule for a pipeline against a fresh scan and list, per rule, the models that match its condition. " +
        "Columns: Rule, Param, Stage, Expected, Matches (matched/checked).")]
    public static Task<string> AuditRunAllSaved(
        [Description("Pipeline id (from daxter_pipelines).")] string pipelineId,
        [Description("Optional: a single model (e.g. 'Sales') — evaluate every saved rule against just that model. Omit for all models.")] string? model = null,
        CancellationToken ct = default)
        => DaxterToolRuntime.AuditRunAllSavedAsync(pipelineId, model, ct);

    // ---- Gated write tools (DRY-RUN by default; enable writes via the web console toggle or DAXTER_MCP_ALLOW_WRITES) ----

    [McpServerTool(Name = "daxter_refresh", Destructive = true, Title = "Refresh model / table / partition"), Description(
        "Refresh a model/table/partition(s). DRY-RUN by default (returns the plan without queueing). " +
        "To run, set execute=true AND enable writes (web console Configure → Allow writes, or DAXTER_MCP_ALLOW_WRITES=true). " +
        "Refreshes are QUEUED onto a shared queue and run by the single worker (the web container), serialized one refresh per " +
        "model (different models run in parallel); this returns a job id — track it with daxter_refresh_jobs. " +
        "If a partition refresh FAILS or is INTERRUPTED, you do NOT need to start over: call " +
        "daxter_resume_refresh(job_id) to pick up where it left off — it re-runs only the not-yet-done partitions. " +
        "(daxter_refresh_jobs also returns a ready-to-use resume_hint for each failed/interrupted job.) " +
        "PROD targets are allowed by default; set DAXTER_MCP_BLOCK_PROD_WRITES=true to re-block them. " +
        "scope=partition refreshes ONE partition; scope=partitions refreshes all of a table's partitions (or the subset in 'partitions'), in order.")]
    public static Task<string> Refresh(
        [Description("Scope: model | table | partition | partitions")] string scope = "model",
        [Description("Table name (required for table/partition/partitions).")] string? table = null,
        [Description("Partition name (required for scope=partition).")] string? partition = null,
        [Description("Comma-separated partition names for scope=partitions (a subset). Omit to refresh ALL partitions of the table.")] string? partitions = null,
        [Description("Refresh type: full|automatic|calculate|dataOnly|clearValues")] string? type = null,
        [Description("Partition order for scope=partitions: newest-first | oldest-first")] string? order = null,
        [Description("Actually queue it (default false = dry run).")] bool execute = false,
        [Description("Retry the refresh up to N times on transient failure (default 0; e.g. 3). Linear backoff.")] int retries = 0,
        [Description("v1.39.0 — also walk the refresh policy on tables that have one. Only valid for scope=model or scope=table. Required after deploying a model to a new environment to materialise the policy-defined partitions. For a SURGICAL alternative that only touches policy tables (no whole-model refresh side effect on non-policy tables), use daxter_apply_refresh_policy.")] bool apply_policy = false,
        string? workspace = null, string? dataset = null, CancellationToken ct = default)
    {
        var s = scope.Trim().ToLowerInvariant();
        var rtype = MaintenanceService.ParseRefreshType(type);

        var (kind, parts) = s switch
        {
            "model" => (RefreshKind.Model, (IReadOnlyList<string>?)null),
            "table" => (RefreshKind.Table, null),
            "partition" => (RefreshKind.Partition, null),
            "partitions" => string.IsNullOrWhiteSpace(partitions)
                ? (RefreshKind.AllPartitions, null)
                : (RefreshKind.SomePartitions,
                    partitions.Split(',', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries)),
            _ => throw new DaxterException($"Unknown scope '{scope}'. Use model | table | partition | partitions."),
        };

        if (kind is RefreshKind.Table or RefreshKind.Partition or RefreshKind.AllPartitions or RefreshKind.SomePartitions
            && string.IsNullOrWhiteSpace(table))
            throw new DaxterException($"table is required for scope={s}.");
        if (kind == RefreshKind.Partition && string.IsNullOrWhiteSpace(partition))
            throw new DaxterException("partition is required for scope=partition.");
        if (apply_policy && kind is RefreshKind.Partition or RefreshKind.AllPartitions or RefreshKind.SomePartitions)
            throw new DaxterException(
                "apply_policy is incompatible with partition-targeted refreshes. Use scope=model or scope=table " +
                "(or call daxter_apply_refresh_policy for the surgical, scoped-to-policy-tables variant).");

        return DaxterToolRuntime.EnqueueRefreshAsync(
            workspace, dataset, kind, table, partition,
            DaxterToolRuntime.ParseOrder(order), rtype, parts, execute, retries, ct,
            applyPolicy: apply_policy, policyTables: null);
    }

    [McpServerTool(Name = "daxter_apply_refresh_policy", Destructive = true, Title = "Apply incremental refresh policy (surgical — Tabular Editor parity)"), Description(
        "v1.39.0 — Apply the incremental refresh policy on tables that have one, mirroring Tabular Editor's " +
        "right-click 'Apply refresh policy'. SURGICAL: only tables WITH a policy are touched — non-policy tables " +
        "are NOT refreshed. Use this after deploying a model to a new environment, where the policy is defined " +
        "but no partitions have been materialised from it yet. Pre-flight enumerates policy tables via XMLA TOM; " +
        "refuses with a clear message if no tables have a policy, or if a specifically-named 'table' has none. " +
        "DRY-RUN by default; set execute=true AND enable writes to queue. PROD-block respects the workspace " +
        "read-only patterns. For a bundled alternative that ALSO refreshes everything else, use daxter_refresh " +
        "with scope=model and apply_policy=true.")]
    public static Task<string> ApplyRefreshPolicy(
        [Description("Optional — apply the policy on just this one table. Refused if the table has no policy. Omit to discover + apply on every policy table in the model.")] string? table = null,
        [Description("Actually queue it (default false = dry run).")] bool execute = false,
        [Description("Retry the refresh up to N times on transient failure (default 0).")] int retries = 0,
        string? workspace = null, string? dataset = null, CancellationToken ct = default)
        => DaxterToolRuntime.ApplyRefreshPolicyAsync(workspace, dataset, table, execute, retries, ct);

    [McpServerTool(Name = "daxter_resume_refresh", Destructive = true, Title = "Resume a refresh job"), Description(
        "Re-run a finished/interrupted/failed refresh job by id (from daxter_refresh_jobs). By DEFAULT resumes " +
        "only the NOT-yet-done partitions (a partition job that recorded its order + progress) — so a 68-partition " +
        "job interrupted at 24 re-runs just the remaining 44 (the failed/in-flight one included). Pass " +
        "remaining_only=false for a full re-run. DRY-RUN unless execute=true AND writes are enabled; queues onto the " +
        "shared worker.")]
    public static Task<string> ResumeRefresh(
        [Description("Job id to resume (from daxter_refresh_jobs).")] int job_id,
        [Description("Resume only the not-yet-done partitions (default true). false = full re-run.")] bool remaining_only = true,
        [Description("Actually queue it (default false = dry run).")] bool execute = false,
        CancellationToken ct = default)
        => DaxterToolRuntime.ResumeRefreshAsync(job_id, remaining_only, execute, ct);

    [McpServerTool(Name = "daxter_refresh_jobs", ReadOnly = true, Title = "List refresh jobs"), Description(
        "List refresh jobs on the shared queue (queued/running/finished) — across ALL interfaces (CLI, MCP, web). " +
        "Pass workspace+dataset to filter to one model. Shows whether a worker is currently running to drain the queue. " +
        "Each FAILED/INTERRUPTED job carries a 'resume_hint' — the exact daxter_resume_refresh call to recover it, " +
        "re-running only the not-yet-done partitions. Use it to self-recover failed refreshes without starting over.")]
    public static string RefreshJobs(
        [Description("Filter to one model's workspace (optional; needs dataset too).")] string? workspace = null,
        [Description("Filter to one model's dataset (optional; needs workspace too).")] string? dataset = null,
        [Description("Most recent N jobs (default 20).")] int top = 20)
        => DaxterToolRuntime.RefreshJobsJson(workspace, dataset, top);

    [McpServerTool(Name = "daxter_clear_cache", Destructive = true, Title = "Clear data cache"), Description(
        "Clear the model's data cache. DRY-RUN by default; requires execute=true AND writes enabled " +
        "(web console Configure → Allow writes, or DAXTER_MCP_ALLOW_WRITES=true).")]
    public static Task<string> ClearCache(
        [Description("Actually execute (default false = dry run).")] bool execute = false,
        [Description("Retry up to N times on transient failure (default 0).")] int retries = 0,
        string? workspace = null, string? dataset = null, CancellationToken ct = default)
        => DaxterToolRuntime.MaintenanceAsync(workspace, dataset, svc => svc.BuildClearCache(), execute, ct, retries);

    [McpServerTool(Name = "daxter_set_refresh_schedule", Destructive = true, Title = "Configure scheduled refresh"), Description(
        "Configure the Power BI Service 'Scheduled refresh' for an IMPORT model: enable/disable, time zone, weekdays, " +
        "time slots, failure email. Only the parameters you set change (partial update). DRY-RUN by default; requires " +
        "execute=true AND writes enabled (web console Configure → Allow writes, or DAXTER_MCP_ALLOW_WRITES=true). " +
        "days = comma weekdays (Monday,Friday); times = comma HH:mm on the hour/half-hour (06:00,12:00); notify = on|off.")]
    public static Task<string> SetRefreshSchedule(
        [Description("Enable (true) or disable (false) scheduled refresh; omit to leave unchanged.")] bool? enabled = null,
        [Description("Comma-separated weekdays, e.g. Monday,Wednesday,Friday (omit to leave unchanged).")] string? days = null,
        [Description("Comma-separated HH:mm slots on the hour/half-hour, e.g. 06:00,12:00 (omit to leave unchanged).")] string? times = null,
        [Description("Time zone id, e.g. \"Pacific Standard Time\" (omit to leave unchanged).")] string? timezone = null,
        [Description("Failure email: on (MailOnFailure) | off (NoNotification) (omit to leave unchanged).")] string? notify = null,
        [Description("Actually apply (default false = dry run).")] bool execute = false,
        string? workspace = null, string? dataset = null, CancellationToken ct = default)
        => DaxterToolRuntime.SetRefreshScheduleAsync(
            workspace, dataset, enabled, Csv(days), Csv(times), timezone, notify, execute, ct);

    private static IReadOnlyList<string>? Csv(string? s)
        => string.IsNullOrWhiteSpace(s)
            ? null
            : s.Split(',', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries);

    // ---- Gated MODEL-EDIT tools (DRY-RUN by default; require execute=true AND model edits enabled —
    //      web console "Allow model edits" or DAXTER_MCP_ALLOW_MODEL_EDIT=true. IRREVERSIBLE for PBIX
    //      download; a .bim backup is written before every apply.) ----

    private const string EditNote =
        " DRY-RUN by default (previews the change; raw TMSL shows the TMSL). To apply, set execute=true AND enable model edits " +
        "(web console Configure → Allow model edits, or DAXTER_MCP_ALLOW_MODEL_EDIT=true). Editing a " +
        "Power BI Desktop model over XMLA is IRREVERSIBLE for PBIX download; a .bim backup is taken first.";

    [McpServerTool(Name = "daxter_edit_measure", Destructive = true, Title = "Create / alter measure"),
     Description("Create or alter a measure (DAX) on a table." + EditNote)]
    public static Task<string> EditMeasure(
        [Description("Table that owns the measure.")] string table,
        [Description("Measure name.")] string name,
        [Description("DAX expression.")] string dax,
        [Description("Format string, e.g. $#,0.00 (optional).")] string? formatString = null,
        [Description("Display folder (optional).")] string? displayFolder = null,
        [Description("Description (optional).")] string? description = null,
        [Description("Actually apply (default false = dry run).")] bool execute = false,
        string? workspace = null, string? dataset = null, CancellationToken ct = default)
        => DaxterToolRuntime.ModelEditAsync(workspace, dataset,
            svc => svc.UpsertMeasure(table, name, dax, formatString, displayFolder, description), execute, ct);

    [McpServerTool(Name = "daxter_delete_measure", Destructive = true, Title = "Delete measure"),
     Description("Delete a measure from a table." + EditNote)]
    public static Task<string> DeleteMeasure(
        [Description("Table that owns the measure.")] string table,
        [Description("Measure name.")] string name,
        [Description("Actually apply (default false = dry run).")] bool execute = false,
        string? workspace = null, string? dataset = null, CancellationToken ct = default)
        => DaxterToolRuntime.ModelEditAsync(workspace, dataset, svc => svc.DeleteMeasure(table, name), execute, ct);

    [McpServerTool(Name = "daxter_set_parameter", Destructive = true, Title = "Set parameter / M expression"),
     Description("Create or alter a shared M expression / parameter (model-level)." + EditNote)]
    public static Task<string> SetParameter(
        [Description("Parameter / expression name.")] string name,
        [Description("The M expression (Power Query).")] string mExpression,
        [Description("Description (optional).")] string? description = null,
        [Description("Actually apply (default false = dry run).")] bool execute = false,
        string? workspace = null, string? dataset = null, CancellationToken ct = default)
        => DaxterToolRuntime.ModelEditAsync(workspace, dataset,
            svc => svc.UpsertExpression(name, mExpression, description), execute, ct);

    [McpServerTool(Name = "daxter_delete_parameter", Destructive = true, Title = "Delete parameter / M expression"),
     Description("Delete a shared M expression / parameter." + EditNote)]
    public static Task<string> DeleteParameter(
        [Description("Parameter / expression name.")] string name,
        [Description("Actually apply (default false = dry run).")] bool execute = false,
        string? workspace = null, string? dataset = null, CancellationToken ct = default)
        => DaxterToolRuntime.ModelEditAsync(workspace, dataset, svc => svc.DeleteExpression(name), execute, ct);

    [McpServerTool(Name = "daxter_edit_role", Destructive = true, Title = "Create / alter RLS role"),
     Description("Create or alter a security (RLS/OLS) role with members and an optional table filter." + EditNote)]
    public static Task<string> EditRole(
        [Description("Role name.")] string name,
        [Description("Model permission: read | readRefresh | refresh | administrator | none (default read).")] string? modelPermission = null,
        [Description("Comma-separated member UPNs / group names (optional).")] string? members = null,
        [Description("Table to apply an RLS filter to (optional).")] string? filterTable = null,
        [Description("DAX filter expression for filterTable, e.g. [Region] = \"US\" (optional).")] string? filterDax = null,
        [Description("Actually apply (default false = dry run).")] bool execute = false,
        string? workspace = null, string? dataset = null, CancellationToken ct = default)
        => DaxterToolRuntime.ModelEditAsync(workspace, dataset, svc => svc.UpsertRole(
            name, modelPermission,
            (members ?? "").Split(',', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries).Select(m => new RoleMember(m)),
            string.IsNullOrWhiteSpace(filterTable) ? null : [new TableFilter(filterTable, filterDax ?? "")]), execute, ct);

    [McpServerTool(Name = "daxter_delete_role", Destructive = true, Title = "Delete RLS role"),
     Description("Delete a security role." + EditNote)]
    public static Task<string> DeleteRole(
        [Description("Role name.")] string name,
        [Description("Actually apply (default false = dry run).")] bool execute = false,
        string? workspace = null, string? dataset = null, CancellationToken ct = default)
        => DaxterToolRuntime.ModelEditAsync(workspace, dataset, svc => svc.DeleteRole(name), execute, ct);

    [McpServerTool(Name = "daxter_edit_calculated_column", Destructive = true, Title = "Create / alter calculated column"),
     Description("Create or alter a calculated column (DAX) on a table." + EditNote)]
    public static Task<string> EditCalculatedColumn(
        [Description("Table that owns the column.")] string table,
        [Description("Column name.")] string name,
        [Description("DAX expression.")] string dax,
        [Description("Data type: string | int64 | double | decimal | dateTime | boolean (optional; inferred if omitted).")] string? dataType = null,
        [Description("Actually apply (default false = dry run).")] bool execute = false,
        string? workspace = null, string? dataset = null, CancellationToken ct = default)
        => DaxterToolRuntime.ModelEditAsync(workspace, dataset,
            svc => svc.UpsertCalculatedColumn(table, name, dax, dataType), execute, ct);

    [McpServerTool(Name = "daxter_edit_column", Destructive = true, Title = "Edit column properties"),
     Description("Edit an EXISTING column's presentation/metadata on any column (data or calculated) — format string, " +
                "data type, sort-by column, summarize-by, display folder, description, hidden, data category — via TOM " +
                "(no DAX needed). This is the path Tabular Editor/Desktop use; raw TMSL can't edit a standalone column. " +
                "Only the properties you pass change (omit to leave as-is; empty string clears a text property)." + EditNote)]
    public static Task<string> EditColumn(
        [Description("Table that owns the column.")] string table,
        [Description("Column name.")] string name,
        [Description("Format string, e.g. \"#,0\" or \"$#,0.00\" or \"0.0%\" (optional).")] string? formatString = null,
        [Description("Data type: string | int64 | double | decimal | dateTime | boolean (optional).")] string? dataType = null,
        [Description("Name of another column on the same table to sort this column by (optional; empty string clears it).")] string? sortByColumn = null,
        [Description("Default summarization: none | sum | average | min | max | count | distinctCount (optional).")] string? summarizeBy = null,
        [Description("Display folder (optional).")] string? displayFolder = null,
        [Description("Description (optional).")] string? description = null,
        [Description("Hide the column from report view (optional).")] bool? isHidden = null,
        [Description("Data category, e.g. Years | Months | Place | WebUrl (optional).")] string? dataCategory = null,
        [Description("Actually apply (default false = dry run).")] bool execute = false,
        string? workspace = null, string? dataset = null, CancellationToken ct = default)
        => DaxterToolRuntime.ModelEditAsync(workspace, dataset,
            svc => svc.EditColumn(table, name, formatString, dataType, sortByColumn, summarizeBy,
                displayFolder, description, isHidden, dataCategory), execute, ct);

    [McpServerTool(Name = "daxter_delete_column", Destructive = true, Title = "Delete column"),
     Description("Delete a column from a table." + EditNote)]
    public static Task<string> DeleteColumn(
        [Description("Table that owns the column.")] string table,
        [Description("Column name.")] string name,
        [Description("Actually apply (default false = dry run).")] bool execute = false,
        string? workspace = null, string? dataset = null, CancellationToken ct = default)
        => DaxterToolRuntime.ModelEditAsync(workspace, dataset, svc => svc.DeleteColumn(table, name), execute, ct);

    [McpServerTool(Name = "daxter_set_partition_source", Destructive = true, Title = "Set partition (M) source"),
     Description("Set a partition's Power Query (M) source expression." + EditNote)]
    public static Task<string> SetPartitionSource(
        [Description("Table that owns the partition.")] string table,
        [Description("Partition name.")] string partition,
        [Description("The M (Power Query) expression for the partition source.")] string mExpression,
        [Description("Actually apply (default false = dry run).")] bool execute = false,
        string? workspace = null, string? dataset = null, CancellationToken ct = default)
        => DaxterToolRuntime.ModelEditAsync(workspace, dataset,
            svc => svc.SetPartitionSource(table, partition, mExpression), execute, ct);

    [McpServerTool(Name = "daxter_create_calculated_table", Destructive = true, Title = "Create calculated table"),
     Description("Create or replace a calculated table (a table whose partition is a DAX expression)." + EditNote)]
    public static Task<string> CreateCalculatedTable(
        [Description("Table name.")] string name,
        [Description("DAX table expression, e.g. CALENDARAUTO().")] string dax,
        [Description("Actually apply (default false = dry run).")] bool execute = false,
        string? workspace = null, string? dataset = null, CancellationToken ct = default)
        => DaxterToolRuntime.ModelEditAsync(workspace, dataset, svc => svc.CreateCalculatedTable(name, dax), execute, ct);

    [McpServerTool(Name = "daxter_delete_table", Destructive = true, Title = "Delete table"),
     Description("Delete an entire table (and its children)." + EditNote)]
    public static Task<string> DeleteTable(
        [Description("Table name.")] string name,
        [Description("Actually apply (default false = dry run).")] bool execute = false,
        string? workspace = null, string? dataset = null, CancellationToken ct = default)
        => DaxterToolRuntime.ModelEditAsync(workspace, dataset, svc => svc.DeleteTable(name), execute, ct);

    [McpServerTool(Name = "daxter_create_import_table", Destructive = true, Title = "Create import table"),
     Description("Create or replace an import table: an M (Power Query) source + typed columns mapped to the M output." + EditNote)]
    public static Task<string> CreateImportTable(
        [Description("Table name.")] string name,
        [Description("The M (Power Query) expression for the partition source.")] string mExpression,
        [Description("Columns as 'Name:dataType:sourceColumn', comma-separated (dataType: string|int64|double|decimal|dateTime|boolean).")] string columns,
        [Description("Actually apply (default false = dry run).")] bool execute = false,
        string? workspace = null, string? dataset = null, CancellationToken ct = default)
        => DaxterToolRuntime.ModelEditAsync(workspace, dataset,
            svc => svc.CreateImportTable(name, mExpression, ParseColumnSpecs(columns)), execute, ct);

    [McpServerTool(Name = "daxter_edit_relationship", Destructive = true, Title = "Create / alter relationship"),
     Description("Create or alter a single-column relationship fromTable[fromColumn] → toTable[toColumn] (many-to-one)." + EditNote)]
    public static Task<string> EditRelationship(
        [Description("'From' (many-side) table.")] string fromTable,
        [Description("'From' column.")] string fromColumn,
        [Description("'To' (one-side) table.")] string toTable,
        [Description("'To' column.")] string toColumn,
        [Description("Relationship name (optional; auto-derived if omitted).")] string? name = null,
        [Description("Cross-filter: single | both | automatic (default single).")] string? crossFilter = null,
        [Description("Whether the relationship is active (default true).")] bool isActive = true,
        [Description("Actually apply (default false = dry run).")] bool execute = false,
        string? workspace = null, string? dataset = null, CancellationToken ct = default)
        => DaxterToolRuntime.ModelEditAsync(workspace, dataset,
            svc => svc.UpsertRelationship(fromTable, fromColumn, toTable, toColumn, name, crossFilter, isActive), execute, ct);

    [McpServerTool(Name = "daxter_delete_relationship", Destructive = true, Title = "Delete relationship"),
     Description("Delete a relationship by name." + EditNote)]
    public static Task<string> DeleteRelationship(
        [Description("Relationship name.")] string name,
        [Description("Actually apply (default false = dry run).")] bool execute = false,
        string? workspace = null, string? dataset = null, CancellationToken ct = default)
        => DaxterToolRuntime.ModelEditAsync(workspace, dataset, svc => svc.DeleteRelationship(name), execute, ct);

    private static IEnumerable<SourceColumn> ParseColumnSpecs(string spec) =>
        (spec ?? "").Split(',', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries)
            .Select(part => part.Split(':', StringSplitOptions.TrimEntries))
            .Select(p => p.Length >= 3
                ? new SourceColumn(p[0], p[1], p[2])
                : throw new DaxterException($"Bad column spec '{string.Join(":", p)}'. Use Name:dataType:sourceColumn."));

    [McpServerTool(Name = "daxter_edit_tmsl", Destructive = true, Title = "Run raw TMSL edit"),
     Description("Execute a raw TMSL command (createOrReplace / alter / delete / …) — the escape hatch for " +
                 "edits not covered by the typed tools." + EditNote)]
    public static Task<string> EditTmsl(
        [Description("A TMSL command object, e.g. {\"createOrReplace\":{\"object\":{...},\"measure\":{...}}}.")] string tmsl,
        [Description("Actually apply (default false = dry run).")] bool execute = false,
        string? workspace = null, string? dataset = null, CancellationToken ct = default)
        => DaxterToolRuntime.ModelEditAsync(workspace, dataset, svc => svc.Raw(tmsl), execute, ct);

    // ---- Fabric SQL endpoints (Warehouse + Lakehouse SQL analytics endpoint) ----

    // ---- Fabric items: Copy Jobs + Notebooks (view + run + monitor) ----

    [McpServerTool(Name = "daxter_copy_jobs", ReadOnly = true, Title = "List Copy Jobs in a workspace"),
     Description("List every Copy Job in a Fabric workspace — id, displayName, description. " +
                 "Pair with daxter_copy_job_definition to see a job's source/destination/mapping JSON, " +
                 "daxter_run_copy_job to execute one on demand, and daxter_item_runs to see its history.")]
    public static Task<string> CopyJobs(string? workspace = null, CancellationToken ct = default)
        => DaxterToolRuntime.CopyJobsAsync(workspace, ct);

    [McpServerTool(Name = "daxter_copy_job_definition", ReadOnly = true, Title = "Show a Copy Job's definition (JSON)"),
     Description("Show the full copyjob-content.json for a Copy Job — same content the Fabric UI shows under \"View JSON code\". " +
                 "Includes the source connection, destination connection, table mappings, type conversions, " +
                 "and (for CDC jobs) the watermark / change-capture config. Read-only.")]
    public static Task<string> CopyJobDefinition(
        [Description("Copy Job item id (GUID; from daxter_copy_jobs).")] string copyJobId,
        string? workspace = null, CancellationToken ct = default)
        => DaxterToolRuntime.CopyJobDefinitionAsync(workspace, copyJobId, ct);

    [McpServerTool(Name = "daxter_notebooks", ReadOnly = true, Title = "List Notebooks in a workspace"),
     Description("List every Notebook in a Fabric workspace — id, displayName, description. " +
                 "Pair with daxter_notebook_definition to read the cells, daxter_run_notebook to execute, " +
                 "and daxter_item_runs to see run history.")]
    public static Task<string> Notebooks(string? workspace = null, CancellationToken ct = default)
        => DaxterToolRuntime.NotebooksAsync(workspace, ct);

    [McpServerTool(Name = "daxter_notebook_definition", ReadOnly = true, Title = "Show a Notebook's definition (ipynb)"),
     Description("Show a Notebook's full definition — the cells, in standard Jupyter ipynb format by default. " +
                 "Pass format=\"FabricGitSource\" to get the language-specific source file instead " +
                 "(notebook-content.py / .scala / .sql / .r). Read-only.")]
    public static Task<string> NotebookDefinition(
        [Description("Notebook item id (GUID; from daxter_notebooks).")] string notebookId,
        [Description("\"ipynb\" (default) or \"FabricGitSource\".")] string? format = null,
        string? workspace = null, CancellationToken ct = default)
        => DaxterToolRuntime.NotebookDefinitionAsync(workspace, notebookId, format, ct);

    [McpServerTool(Name = "daxter_run_copy_job", Destructive = false, Title = "Run a Copy Job on demand (gated)"),
     Description("Start an on-demand run of a Copy Job. DRY RUN by default — pass execute=true to actually run. " +
                 "The workspace + writes gates (Allow writes + non-PROD) apply same as other mutations. " +
                 "Returns the new instance id; poll daxter_item_job_status to track it.")]
    public static Task<string> RunCopyJob(
        [Description("Copy Job item id.")] string copyJobId,
        [Description("Actually start the run (default false = dry run).")] bool execute = false,
        string? workspace = null, CancellationToken ct = default)
        => DaxterToolRuntime.RunItemJobAsync(workspace, copyJobId, "Execute", null, execute, ct);

    [McpServerTool(Name = "daxter_run_notebook", Destructive = false, Title = "Run a Notebook on demand (gated)"),
     Description("Start an on-demand run of a Notebook. DRY RUN by default — pass execute=true to actually run. " +
                 "Pass executionData as a JSON string for parameterized runs " +
                 "(e.g. '{\"parameters\":{\"x\":{\"value\":\"2026-06-01\",\"type\":\"string\"}}}'). " +
                 "The workspace + writes gates (Allow writes + non-PROD) apply.")]
    public static Task<string> RunNotebook(
        [Description("Notebook item id.")] string notebookId,
        [Description("Actually start the run (default false = dry run).")] bool execute = false,
        [Description("Optional JSON payload for parameterization / session config (see Fabric Job Scheduler docs).")] string? executionData = null,
        string? workspace = null, CancellationToken ct = default)
        => DaxterToolRuntime.RunItemJobAsync(workspace, notebookId, "RunNotebook", executionData, execute, ct);

    [McpServerTool(Name = "daxter_item_runs", ReadOnly = true, Title = "Recent runs for any Fabric item"),
     Description("List recent job-instance runs for ANY Fabric item — Copy Job, Notebook, Pipeline. " +
                 "Returns one row per run: instanceId, status (NotStarted | InProgress | Completed | Failed | Cancelled), " +
                 "invokeType (Manual | Scheduled), startTimeUtc, endTimeUtc, durationSec, failureReason. " +
                 "Use to inspect history or find an instanceId for daxter_cancel_item_job / daxter_item_job_status.")]
    public static Task<string> ItemRuns(
        [Description("Item id (Copy Job / Notebook / Pipeline / …).")] string itemId,
        string? workspace = null, CancellationToken ct = default)
        => DaxterToolRuntime.ItemRunsAsync(workspace, itemId, ct);

    [McpServerTool(Name = "daxter_item_job_status", ReadOnly = true, Title = "Get one job-instance's status"),
     Description("Get the detailed status of a single item-job instance — typed view of the run record. " +
                 "Use to poll a run started by daxter_run_copy_job / daxter_run_notebook until it reaches a " +
                 "terminal state (Completed | Failed | Cancelled).")]
    public static Task<string> ItemJobStatus(
        [Description("Item id.")] string itemId,
        [Description("Job instance id (from daxter_run_* or daxter_item_runs).")] string instanceId,
        string? workspace = null, CancellationToken ct = default)
        => DaxterToolRuntime.ItemJobStatusAsync(workspace, itemId, instanceId, ct);

    [McpServerTool(Name = "daxter_cancel_item_job", Destructive = false, Title = "Cancel a running job instance (gated)"),
     Description("Cancel a running item-job instance. DRY RUN by default — pass execute=true to actually cancel. " +
                 "Writes gate applies. After cancel, the next daxter_item_job_status should report 'Cancelled'.")]
    public static Task<string> CancelItemJob(
        [Description("Item id.")] string itemId,
        [Description("Job instance id.")] string instanceId,
        [Description("Actually cancel (default false = dry run).")] bool execute = false,
        string? workspace = null, CancellationToken ct = default)
        => DaxterToolRuntime.CancelItemJobAsync(workspace, itemId, instanceId, execute, ct);

    [McpServerTool(Name = "daxter_sql_endpoints", ReadOnly = true, Title = "List Fabric SQL endpoints"),
     Description("List every Fabric SQL endpoint in a workspace — each Warehouse and each Lakehouse's SQL analytics endpoint — " +
                 "with name, server (TDS hostname), database, and kind (Warehouse | Lakehouse). " +
                 "Call this FIRST to discover targets for daxter_sql_query; you pass the friendly name back, no GUID hostname required.")]
    public static Task<string> SqlEndpoints(
        [Description("Workspace name or id (optional; defaults to server config).")] string? workspace = null,
        CancellationToken ct = default)
        => DaxterToolRuntime.SqlEndpointsAsync(workspace, ct);

    [McpServerTool(Name = "daxter_sql_objects", ReadOnly = true, Title = "List SQL endpoint objects (schemas + tables/views/functions/procs)"),
     Description("List every schema and every Table / View / Function / Stored Procedure on a Fabric SQL endpoint, " +
                 "as (schema, kind, name) rows. One INFORMATION_SCHEMA round-trip; resolves the endpoint NAME (from " +
                 "daxter_sql_endpoints) into the server/database for you. " +
                 "Use this before daxter_sql_query to discover what's queryable — pick a table, then SELECT from it.")]
    public static Task<string> SqlObjects(
        [Description("Workspace name or id.")] string workspace,
        [Description("Warehouse or Lakehouse name (from daxter_sql_endpoints).")] string endpoint,
        CancellationToken ct = default)
        => DaxterToolRuntime.SqlObjectsAsync(workspace, endpoint, ct);

    [McpServerTool(Name = "daxter_sql_export", ReadOnly = true, Title = "Export full T-SQL result set as CSV (streaming)"),
     Description("Stream a Fabric SQL endpoint query's FULL result set as CSV to a file on DAXter's persistent volume " +
                 "(~/.daxter/exports/sql/). Use this instead of daxter_sql_query when you want every row — " +
                 "daxter_sql_query materializes the result set in memory and is meant for sampling; daxter_sql_export " +
                 "streams row-by-row straight to disk, so SELECT * on a multi-million-row table won't OOM. " +
                 "Returns the on-disk path and row count; tell the user to docker cp it off the container, or mount " +
                 "the daxter-tokens volume on a host path to get the file directly. Same writes-gate as daxter_sql_query. " +
                 "Pass quoteAll=true and/or crlf=true to match Power BI / Excel \"Export data\" style (quote every " +
                 "field, CRLF line endings) when the downstream consumer needs that exact format.")]
    public static Task<string> SqlExport(
        [Description("Workspace name or id.")] string workspace,
        [Description("Warehouse or Lakehouse name (from daxter_sql_endpoints).")] string endpoint,
        [Description("T-SQL statement (typically a SELECT).")] string sql,
        [Description("Wrap every field in quotes (Power BI / Excel \"Export data\" style). Default false = RFC 4180 quote-when-needed.")] bool quoteAll = false,
        [Description("End lines with CRLF (\\r\\n) instead of LF (\\n). Excel-on-Windows convention. Default false.")] bool crlf = false,
        [Description("Optional — also mirror the CSV into the artifact store under this key (e.g. 'sql/exports/sales-2026-06-09.csv') so daxter_artifact_get can fetch it without docker cp.")] string? artifactKey = null,
        CancellationToken ct = default)
        => DaxterToolRuntime.SqlExportAsync(workspace, endpoint, sql, ct, quoteAll, crlf, artifactKey);

    [McpServerTool(Name = "daxter_sql_query", ReadOnly = true, Title = "Run T-SQL on a Fabric SQL endpoint"),
     Description("Run T-SQL on a Fabric Warehouse or Lakehouse SQL endpoint. Pass the workspace and the endpoint NAME " +
                 "(from daxter_sql_endpoints) — the tool resolves the server + database for you. " +
                 "Authenticates with the same MSAL account daxter_login signs in (no separate sign-in for SQL). " +
                 "READ-ONLY by default — SELECT/EXPLAIN/SHOW/CTE-feeding-SELECT runs unconditionally. " +
                 "INSERT/UPDATE/DELETE/MERGE/DDL/EXEC is REFUSED unless the writes gate is on " +
                 "(Configure → Allow writes, or DAXTER_MCP_ALLOW_WRITES=true) AND the workspace doesn't look like PROD.")]
    public static Task<string> SqlQuery(
        [Description("Workspace name or id.")] string workspace,
        [Description("Warehouse or Lakehouse name (from daxter_sql_endpoints).")] string endpoint,
        [Description("T-SQL statement(s).")] string sql,
        CancellationToken ct = default)
        => DaxterToolRuntime.SqlQueryAsync(workspace, endpoint, sql, ct);

    // ── Artifact store ────────────────────────────────────────────────────────────────────────
    // The transport-agnostic file plane. Every file-shaped DAXter feature (PBIR exports, SQL
    // CSVs, future definition uploads) goes through here, so any agent — local or remote —
    // gets to bytes through the same MCP surface. See src/Daxter.Core/Artifacts/ArtifactStore.cs.

    [McpServerTool(Name = "daxter_artifact_list", ReadOnly = true, Title = "List artifacts in the local store"),
     Description("List artifacts persisted by other DAXter tools (PBIR exports from daxter_export_report, " +
                 "CSV exports from daxter_sql_export, future definition bundles). Pass `prefix` to narrow the scan " +
                 "(e.g. 'reports/' / 'sql/' / 'alignment/'). Returns key, byte size, created/expires timestamps, and " +
                 "the source tool that produced each entry — plus the store's current usage / quota. " +
                 "Use this to discover what's available before calling daxter_artifact_get / _bundle.")]
    public static Task<string> ArtifactList(
        [Description("Optional key prefix to narrow the listing (e.g. 'reports/sales/').")] string? prefix = null,
        CancellationToken ct = default)
        => DaxterToolRuntime.ArtifactListAsync(prefix, ct);

    [McpServerTool(Name = "daxter_artifact_get", ReadOnly = true, Title = "Download one artifact's content"),
     Description("Download a single artifact's bytes. Returns the content INLINE as base64 when ≤ 10 MB " +
                 "(JSON envelope with content_base64, inline=true) — caller decodes it directly. " +
                 "Above 10 MB the response carries a download_url (relative to the DAXter web host) for the " +
                 "agent to fetch via plain GET — that path streams the file with no MCP overhead. " +
                 "Pair with daxter_artifact_list to discover keys first.")]
    public static Task<string> ArtifactGet(
        [Description("Artifact key — forward-slash path, e.g. 'reports/sales/report.json'.")] string key,
        CancellationToken ct = default)
        => DaxterToolRuntime.ArtifactGetAsync(key, ct);

    [McpServerTool(Name = "daxter_artifact_bundle", ReadOnly = true, Title = "Zip a prefix and download it"),
     Description("Zip every artifact under a prefix into one archive and download it. Mirrors the single-file " +
                 "daxter_artifact_get behavior: inline base64 when the uncompressed total is ≤ 10 MB, otherwise " +
                 "a download_url pointing at the streaming /api/artifacts/{prefix}?bundle=1 endpoint. " +
                 "Use this to grab whole PBIR folders (every visual.json + report.json + pages/) in one shot — " +
                 "the typical flow for the Power BI alignment-check skill.")]
    public static Task<string> ArtifactBundle(
        [Description("Key prefix to bundle, e.g. 'reports/sales-dashboard' bundles every file under reports/sales-dashboard/.")] string prefix,
        CancellationToken ct = default)
        => DaxterToolRuntime.ArtifactBundleAsync(prefix, ct);

    [McpServerTool(Name = "daxter_artifact_meta", ReadOnly = true, Title = "Show one artifact's metadata"),
     Description("Show just the metadata (size, created, TTL, source tool) for one artifact key — without " +
                 "downloading bytes. Cheap; use this to decide whether to fetch or to confirm an artifact is " +
                 "still in the store before referencing it in a later step.")]
    public static Task<string> ArtifactMeta(
        [Description("Artifact key.")] string key,
        CancellationToken ct = default)
        => DaxterToolRuntime.ArtifactMetaAsync(key, ct);

    [McpServerTool(Name = "daxter_artifact_delete", Destructive = true, Title = "Delete an artifact or prefix"),
     Description("Delete a single artifact OR every artifact under a key prefix (recursive). The user's local " +
                 "data — NOT gated on the Allow-writes / prod-block guards (those are for Power BI mutations). " +
                 "Always echo back to the user what you're about to delete and CONFIRM before calling — once " +
                 "executed the bytes are gone. Returns the count removed.")]
    public static Task<string> ArtifactDelete(
        [Description("Artifact key OR key prefix (deletes everything under it).")] string keyPrefix,
        CancellationToken ct = default)
        => DaxterToolRuntime.ArtifactDeleteAsync(keyPrefix, ct);

    [McpServerTool(Name = "daxter_artifact_put", Title = "Upload one file into the artifact store"),
     Description("Upload bytes INTO the artifact store. Pass EITHER `contentBase64` (inline — best for small payloads " +
                 "≤ a few MB) OR `fetchUrl` (the DAXter daemon fetches the URL itself — best for big files; the URL " +
                 "must be reachable from inside the DAXter container). Optional `ttlHours` attaches a TTL so the " +
                 "nightly purge sweeps it; omit for an immortal artifact. Source-tool stamp defaults to 'daxter_artifact_put' " +
                 "— override via `sourceTool` (e.g. 'powerbi_alignment_fix') so the /artifacts page shows provenance. " +
                 "Returns the stored ArtifactRef (key, bytes, created_utc, expires_utc, source_tool). " +
                 "Quota refusal is returned as a REFUSED message — list/delete to free space, then retry.")]
    public static Task<string> ArtifactPut(
        [Description("Artifact key — forward-slash path, e.g. 'reports/sales/page.json'.")] string key,
        [Description("Inline payload as base64 (pick this for small content). Mutually exclusive with fetchUrl.")] string? contentBase64 = null,
        [Description("URL the DAXter daemon will GET to obtain the payload (pick this for large content). Mutually exclusive with contentBase64.")] string? fetchUrl = null,
        [Description("Optional TTL in hours — artifact expires and is swept by the nightly purge.")] double? ttlHours = null,
        [Description("Optional source-tool label, e.g. 'powerbi_alignment_fix'.")] string? sourceTool = null,
        CancellationToken ct = default)
        => DaxterToolRuntime.ArtifactPutAsync(key, contentBase64, fetchUrl, ttlHours, sourceTool, ct);

    // ── Fabric write-backs (Phase 3) ──────────────────────────────────────────────────────────
    // Close the round-trip: agent prepares a corrected item definition in the artifact store,
    // these tools publish it to Fabric. Each is gated like every other DAXter write — dry-run
    // unless execute=true AND writes are enabled AND the workspace isn't read-only.

    [McpServerTool(Name = "daxter_update_report_definition", Destructive = true, Title = "Update a report's PBIR definition"),
     Description("Publish a corrected PBIR definition from the artifact store back to a Fabric Report. " +
                 "READS every artifact under `artifact_key_prefix` (forward-slash path; e.g. " +
                 "'alignment/sales-dashboard-fixed') — each artifact's relative path becomes a PBIR part path. " +
                 "POSTs to /v1/workspaces/{ws}/reports/{id}/updateDefinition. Use the artifact-store flow: " +
                 "1) daxter_export_report with artifact_key= → grab original. 2) powerbi-alignment-fix (or " +
                 "your own edit) → write corrected to artifact prefix via daxter_artifact_extract / _put. " +
                 "3) THIS TOOL with execute=true. Gated: dry-run unless execute=true AND writes are enabled " +
                 "(Configure → Allow writes / DAXTER_MCP_ALLOW_WRITES=true) AND the workspace isn't read-only.")]
    public static Task<string> UpdateReportDefinition(
        [Description("Report name or id (GUID). For names, the workspace listing resolves the id.")] string report,
        [Description("Artifact key prefix — every artifact under it becomes a PBIR part.")] string artifact_key_prefix,
        [Description("Actually publish (default false = dry run).")] bool execute = false,
        [Description("Workspace name or id (optional; defaults to server config).")] string? workspace = null,
        CancellationToken ct = default)
        => DaxterToolRuntime.UpdateItemDefinitionAsync(workspace, report,
            PowerBiRestClient.FabricItemKinds.Report, artifact_key_prefix, execute, ct);

    [McpServerTool(Name = "daxter_update_notebook_definition", Destructive = true, Title = "Update a notebook's definition"),
     Description("Publish a corrected Notebook definition (ipynb cells + .platform) from the artifact store " +
                 "back to a Fabric Notebook. Reads every artifact under `artifact_key_prefix` (e.g. " +
                 "'notebooks/etl/fixed') and POSTs to /v1/workspaces/{ws}/notebooks/{id}/updateDefinition. " +
                 "REQUIRES the notebook id (GUID) — use daxter_notebooks to find it. Same writes gate as " +
                 "daxter_update_report_definition: dry-run unless execute=true + Allow writes + workspace " +
                 "not read-only.")]
    public static Task<string> UpdateNotebookDefinition(
        [Description("Notebook id (GUID — from daxter_notebooks).")] string notebook_id,
        [Description("Artifact key prefix carrying the new notebook parts.")] string artifact_key_prefix,
        [Description("Actually publish (default false = dry run).")] bool execute = false,
        [Description("Workspace name or id.")] string? workspace = null,
        CancellationToken ct = default)
        => DaxterToolRuntime.UpdateItemDefinitionAsync(workspace, notebook_id,
            PowerBiRestClient.FabricItemKinds.Notebook, artifact_key_prefix, execute, ct);

    [McpServerTool(Name = "daxter_update_copy_job_definition", Destructive = true, Title = "Update a Copy Job's definition"),
     Description("Publish a corrected Copy Job definition (copyjob-content.json + .platform) from the " +
                 "artifact store back to a Fabric Copy Job. Reads every artifact under `artifact_key_prefix` " +
                 "and POSTs to /v1/workspaces/{ws}/copyJobs/{id}/updateDefinition. REQUIRES the copy-job id " +
                 "(GUID — from daxter_copy_jobs). Same writes gate as the report/notebook variants.")]
    public static Task<string> UpdateCopyJobDefinition(
        [Description("Copy Job id (GUID — from daxter_copy_jobs).")] string copy_job_id,
        [Description("Artifact key prefix carrying the new copy-job parts.")] string artifact_key_prefix,
        [Description("Actually publish (default false = dry run).")] bool execute = false,
        [Description("Workspace name or id.")] string? workspace = null,
        CancellationToken ct = default)
        => DaxterToolRuntime.UpdateItemDefinitionAsync(workspace, copy_job_id,
            PowerBiRestClient.FabricItemKinds.CopyJob, artifact_key_prefix, execute, ct);

    // ── Context (shared knowledge plane — Phase 4) ────────────────────────────────────────────
    // Sits on top of the artifact store under the `context/` prefix. Text-not-base64 by design —
    // these payloads are markdown / prose / prompts, never .pbix bytes. Conventional namespaces:
    //   clients/<client>/      — per-client glossary + conventions
    //   workspaces/<ws>/       — per-workspace context (auto-attached to daxter_query)
    //   endpoints/<ws>/<ep>/   — per-Fabric-SQL-endpoint cards (auto-attached to daxter_sql_query)
    //   skills/<topic>/        — reusable knowledge snippets (DAX patterns, SQL cheatsheets)
    //   conventions/           — global rules
    //   incidents/<ticket>/    — active investigations
    //
    // Multi-session use case: agent A writes the team glossary → agent B (later, same DAXter
    // instance) reads it via daxter_context_get or sees it auto-attached on the next workspace
    // query. With a shared volume / hosted DAXter, this becomes the team knowledge plane.

    [McpServerTool(Name = "daxter_context_list", ReadOnly = true, Title = "List shared-knowledge context entries"),
     Description("List context entries — curated team knowledge (glossaries, conventions, prompts, " +
                 "skills, troubleshooting playbooks) shared across all MCP sessions connected to this " +
                 "DAXter. Optional `namespace_path` narrows the scan (e.g. 'clients/acme/' or 'skills/dax/'). " +
                 "Returns metadata only — call daxter_context_get for the body. Common namespaces: " +
                 "clients/<name>/, workspaces/<ws>/, endpoints/<ws>/<ep>/, skills/<topic>/, conventions/, " +
                 "incidents/<ticket>/. Cards under workspaces/<ws>/ and endpoints/<ws>/<ep>/ are " +
                 "auto-attached to daxter_query / daxter_sql_query against that target.")]
    public static Task<string> ContextList(
        [Description("Optional sub-namespace (e.g. 'clients/acme' or 'skills').")] string? namespace_path = null,
        CancellationToken ct = default)
        => DaxterToolRuntime.ContextListAsync(namespace_path, ct);

    [McpServerTool(Name = "daxter_context_get", ReadOnly = true, Title = "Read a shared-knowledge context entry"),
     Description("Fetch a single context entry's full text. Returns content directly (not base64) for " +
                 "entries up to 1 MB. Above that, `too_large_for_inline=true` and the agent should fetch " +
                 "via GET /api/artifacts/context/{key} on the DAXter web host. Use daxter_context_list " +
                 "to discover available keys; daxter_context_search to find content by keyword.")]
    public static Task<string> ContextGet(
        [Description("Context key WITHOUT the 'context/' prefix (e.g. 'clients/acme/glossary.md').")] string key,
        CancellationToken ct = default)
        => DaxterToolRuntime.ContextGetAsync(key, ct);

    [McpServerTool(Name = "daxter_context_put", Title = "Create or update a shared-knowledge context entry"),
     Description("Write text content into the shared-knowledge plane — visible to every MCP session " +
                 "connected to this DAXter. Use for team glossaries, client conventions, DAX/SQL pattern " +
                 "libraries, troubleshooting playbooks, prompts. ALWAYS confirm with the user before " +
                 "writing — once published, every future session reads it. Optional `source_tool` stamps " +
                 "provenance ('team-curator', 'powerbi_alignment_fix'); optional `ttl_hours` attaches an " +
                 "expiry (e.g. for incident-specific notes that should self-expire after the ticket closes).")]
    public static Task<string> ContextPut(
        [Description("Context key WITHOUT the 'context/' prefix (e.g. 'clients/acme/glossary.md').")] string key,
        [Description("Text content (markdown / prose / prompt template). Use daxter_artifact_put for binary bytes.")] string content,
        [Description("Optional provenance label (e.g. 'team-curator', 'dgonzalez').")] string? source_tool = null,
        [Description("Optional TTL in hours — nightly purge sweeps the entry after this.")] double? ttl_hours = null,
        CancellationToken ct = default)
        => DaxterToolRuntime.ContextPutAsync(key, content, source_tool, ttl_hours, ct);

    [McpServerTool(Name = "daxter_context_search", ReadOnly = true, Title = "Search the shared-knowledge plane"),
     Description("Case-insensitive substring search across both keys and bodies of every context entry. " +
                 "Returns matched keys + a snippet of the matched line in context + a match count for " +
                 "ranking. Use to discover relevant facts before answering a question — e.g. 'TLA' to find " +
                 "any glossary entry mentioning that acronym. Pathological-size bodies (>256 KB) are skipped " +
                 "during body scan; their keys still match.")]
    public static Task<string> ContextSearch(
        [Description("Substring to search for (case-insensitive).")] string query,
        CancellationToken ct = default)
        => DaxterToolRuntime.ContextSearchAsync(query, ct);

    [McpServerTool(Name = "daxter_context_delete", Destructive = true, Title = "Delete a shared-knowledge context entry"),
     Description("Delete a context entry, or every entry under a sub-namespace (recursive). Like " +
                 "daxter_artifact_delete this is NOT gated on Allow-writes (user's own curated text). " +
                 "ALWAYS confirm with the user first — once gone, every future session loses access to " +
                 "the fact. Use the dry-run path: daxter_context_list with the same prefix to preview.")]
    public static Task<string> ContextDelete(
        [Description("Context key OR sub-namespace (deletes recursively, WITHOUT the 'context/' prefix).")] string key_or_namespace,
        CancellationToken ct = default)
        => DaxterToolRuntime.ContextDeleteAsync(key_or_namespace, ct);

    [McpServerTool(Name = "daxter_artifact_extract", Title = "Unzip an archive into the artifact store"),
     Description("Unzip a zip archive INTO the artifact store under a key prefix — every entry becomes a separate " +
                 "artifact at `<keyPrefix>/<entry.path>`. Same dual-mode payload as daxter_artifact_put: pass " +
                 "EITHER `zipBase64` (inline) OR `fetchUrl` (daemon fetches). The typical flow for the Power BI " +
                 "alignment workflow: powerbi-alignment-fix produces a corrected PBIR folder → zip it → " +
                 "extract here under 'alignment/sales-dashboard-fixed' → Phase 3 daxter_update_report_definition " +
                 "pushes it back to Fabric. Same TTL + source-tool plumbing as Put.")]
    public static Task<string> ArtifactExtract(
        [Description("Key prefix to unzip into, e.g. 'alignment/sales-dashboard-fixed'.")] string keyPrefix,
        [Description("Inline zip payload as base64. Mutually exclusive with fetchUrl.")] string? zipBase64 = null,
        [Description("URL the DAXter daemon will GET to obtain the zip. Mutually exclusive with zipBase64.")] string? fetchUrl = null,
        [Description("Optional TTL in hours — every extracted entry inherits this expiry.")] double? ttlHours = null,
        [Description("Optional source-tool label, e.g. 'powerbi_alignment_fix'.")] string? sourceTool = null,
        CancellationToken ct = default)
        => DaxterToolRuntime.ArtifactExtractAsync(keyPrefix, zipBase64, fetchUrl, ttlHours, sourceTool, ct);
}
