using System.ComponentModel;
using System.Text;
using Daxter.Core;
using Daxter.Core.Editing;
using Daxter.Core.Maintenance;
using Daxter.Core.Scheduling;
using ModelContextProtocol.Server;

namespace Daxter.Cli.Mcp;

/// <summary>
/// MCP tools over the Power BI Service. Most accept optional <c>workspace</c>/<c>dataset</c>
/// arguments (name or id) that override the server's config. Read tools are annotated
/// <c>ReadOnly = true</c>; the two mutating tools (<c>daxter_refresh</c>, <c>daxter_clear_cache</c>)
/// are annotated <c>Destructive = true</c> and stay dry-run unless writes are explicitly enabled.
/// </summary>
[McpServerToolType]
public static class DaxterTools
{
    [McpServerTool(Name = "daxter_capabilities", ReadOnly = true, Title = "List all DAXter features/tools"), Description(
        "List EVERY DAXter tool — name, title, whether it reads or writes, and what it does — plus the running version. " +
        "Call this FIRST to discover the full set of features in one shot: query/DAX, metadata, refresh + resume, model " +
        "editing, connections, report export/classification, pipelines, audits, gateways. Always complete and current — " +
        "it is generated by reflecting the registered tools at runtime, so every release automatically surfaces its new " +
        "features here. Use it whenever you're unsure what DAXter can do.")]
    public static string Capabilities() => DaxterToolRuntime.CapabilitiesJson();

    [McpServerTool(Name = "daxter_login", Title = "Sign in to Power BI (and optionally Fabric SQL)"),
     Description("Sign in interactively (device code). Returns a URL and a code to enter in your browser; once you complete it, the other tools run as you. " +
                 "Call this if a tool reports 'Not signed in'. " +
                 "Pass target=\"sql\" to sign in for Fabric Warehouse / Lakehouse SQL endpoints — that's a SEPARATE one-time sign-in (different pre-authorized client id) because Power BI's first-party client id isn't authorized for database.windows.net (AADSTS65002). " +
                 "(No effect when the server uses a service principal.)")]
    public static Task<string> Login(
        [Description("Sign-in target: \"powerbi\" (default — XMLA + REST) or \"sql\" (Fabric SQL endpoint).")] string? target = null,
        CancellationToken ct = default)
        => DaxterToolRuntime.LoginAsync(ct, target);

    [McpServerTool(Name = "daxter_query", ReadOnly = true, Title = "Run DAX/MDX query"), Description("Run a DAX or MDX query against a Power BI semantic model. Returns rows as JSON.")]
    public static Task<string> Query(
        [Description("The DAX or MDX query, e.g. EVALUATE TOPN(10, Sales)")] string query,
        [Description("Workspace name or id/GUID (optional; defaults to server config)")] string? workspace = null,
        [Description("Dataset / model name or id/GUID (optional; defaults to server config). Pass names with apostrophes as-is.")] string? dataset = null,
        CancellationToken ct = default)
        => DaxterToolRuntime.XmlaAsync(workspace, dataset, s => s.Execute(query), ct);

    [McpServerTool(Name = "daxter_dmv", ReadOnly = true, Title = "Run DMV query"), Description("Run a DMV ($SYSTEM) query, e.g. SELECT * FROM $SYSTEM.TMSCHEMA_TABLES.")]
    public static Task<string> Dmv(
        [Description("A DMV SELECT statement.")] string statement,
        string? workspace = null, string? dataset = null, CancellationToken ct = default)
        => DaxterToolRuntime.XmlaAsync(workspace, dataset, s => s.Execute(statement), ct);

    [McpServerTool(Name = "daxter_list_tables", ReadOnly = true, Title = "List tables"), Description("List the tables in a semantic model.")]
    public static Task<string> ListTables(string? workspace = null, string? dataset = null, CancellationToken ct = default)
        => DaxterToolRuntime.XmlaAsync(workspace, dataset,
            s => s.Execute("SELECT [Name] AS [Table] FROM $SYSTEM.TMSCHEMA_TABLES ORDER BY [Name]"), ct);

    [McpServerTool(Name = "daxter_measures", ReadOnly = true, Title = "List measures"), Description("List measures in a model. Set withExpression=true to include the DAX.")]
    public static Task<string> Measures(
        [Description("Include each measure's DAX expression.")] bool withExpression = false,
        string? workspace = null, string? dataset = null, CancellationToken ct = default)
        => DaxterToolRuntime.MetaAsync(workspace, dataset, m => m.Measures(withExpression), ct);

    [McpServerTool(Name = "daxter_measure", ReadOnly = true, Title = "Show measure definition"), Description("Show one measure's full definition (name, type, folder, format, DAX).")]
    public static Task<string> Measure(
        [Description("Measure name.")] string name,
        string? workspace = null, string? dataset = null, CancellationToken ct = default)
        => DaxterToolRuntime.MetaAsync(workspace, dataset, m => m.Measure(name), ct);

    [McpServerTool(Name = "daxter_mcode", ReadOnly = true, Title = "Show Power Query (M)"), Description("Show the Power Query (M) code for a table's partitions.")]
    public static Task<string> MCode(
        [Description("Table name.")] string table,
        string? workspace = null, string? dataset = null, CancellationToken ct = default)
        => DaxterToolRuntime.MetaAsync(workspace, dataset, m => m.MCode(table), ct);

    [McpServerTool(Name = "daxter_parameters", ReadOnly = true, Title = "List parameters"), Description("List the model's shared M expressions / parameters.")]
    public static Task<string> Parameters(string? workspace = null, string? dataset = null, CancellationToken ct = default)
        => DaxterToolRuntime.MetaAsync(workspace, dataset, m => m.Parameters(), ct);

    [McpServerTool(Name = "daxter_partitions", ReadOnly = true, Title = "List partitions"), Description("List partitions and last-refresh times, optionally for one table.")]
    public static Task<string> Partitions(
        [Description("Table name (optional; all partitions if omitted).")] string? table = null,
        string? workspace = null, string? dataset = null, CancellationToken ct = default)
        => DaxterToolRuntime.MetaAsync(workspace, dataset, m => m.Partitions(table), ct);

    [McpServerTool(Name = "daxter_columns", ReadOnly = true, Title = "List columns"), Description("List columns in a model (name, data type, hidden), optionally for one table. Excludes the internal RowNumber column.")]
    public static Task<string> Columns(
        [Description("Table name (optional; all columns with their table id if omitted).")] string? table = null,
        string? workspace = null, string? dataset = null, CancellationToken ct = default)
        => DaxterToolRuntime.MetaAsync(workspace, dataset, m => m.Columns(table), ct);

    [McpServerTool(Name = "daxter_rls", ReadOnly = true, Title = "List RLS roles"), Description("List RLS roles in a model.")]
    public static Task<string> Rls(string? workspace = null, string? dataset = null, CancellationToken ct = default)
        => DaxterToolRuntime.MetaAsync(workspace, dataset, m => m.Roles(), ct);

    [McpServerTool(Name = "daxter_diff_measures", ReadOnly = true, Title = "Compare measures"), Description("Compare measures between the configured model and another model in the same workspace.")]
    public static Task<string> DiffMeasures(
        [Description("The other dataset/model name to compare against.")] string other,
        string? workspace = null, string? dataset = null, CancellationToken ct = default)
        => DaxterToolRuntime.DiffMeasuresAsync(workspace, dataset, other, ct);

    [McpServerTool(Name = "daxter_refresh_history", ReadOnly = true, Title = "Refresh history"), Description("Show recent refresh history (status, start/end) for a model via REST.")]
    public static Task<string> RefreshHistory(
        [Description("Number of recent refreshes (default 10).")] int top = 10,
        string? workspace = null, string? dataset = null, CancellationToken ct = default)
        => DaxterToolRuntime.RestAsync(workspace, dataset, async (rest, cfg, c) =>
        {
            var groupId = await rest.ResolveGroupIdAsync(cfg.Workspace, c);
            var datasetId = await rest.ResolveDatasetIdAsync(groupId, cfg.Dataset!, c);
            return await rest.RefreshHistoryAsync(groupId, datasetId, top, c);
        }, ct);

    [McpServerTool(Name = "daxter_workspaces", ReadOnly = true, Title = "List workspaces"), Description("List Power BI workspaces (with their group ids) the identity can see. No workspace needs to be configured first.")]
    public static Task<string> Workspaces(CancellationToken ct = default)
        => DaxterToolRuntime.RestTenantAsync((rest, c) => rest.GroupsAsync(c), ct);

    [McpServerTool(Name = "daxter_datasets", ReadOnly = true, Title = "List datasets"), Description("List datasets in a workspace.")]
    public static Task<string> Datasets(string? workspace = null, CancellationToken ct = default)
        => DaxterToolRuntime.RestAsync(workspace, null, async (rest, cfg, c) =>
            await rest.DatasetsAsync(await rest.ResolveGroupIdAsync(cfg.Workspace, c), c), ct);

    [McpServerTool(Name = "daxter_reports", ReadOnly = true, Title = "List reports"), Description("List reports in a workspace.")]
    public static Task<string> Reports(string? workspace = null, CancellationToken ct = default)
        => DaxterToolRuntime.RestAsync(workspace, null, async (rest, cfg, c) =>
            await rest.ReportsAsync(await rest.ResolveGroupIdAsync(cfg.Workspace, c), c), ct);

    // ---- take ownership + gateway binding (service config; XMLA can't do these) ----

    [McpServerTool(Name = "daxter_connections", ReadOnly = true, Title = "List all connections"), Description("List every connection you can access (shareable cloud + on-prem/VNet gateway) via the Fabric API: id, display name, connectivity type, and details. Use to find shareable cloud connections independent of any model.")]
    public static Task<string> Connections(CancellationToken ct = default)
        => DaxterToolRuntime.RestTenantAsync((rest, c) => rest.ConnectionsAsync(c), ct);

    [McpServerTool(Name = "daxter_report_inventory", ReadOnly = true, Title = "Classify reports (thin/thick + downloadable)"), Description("Classify every report in a workspace as thin (decoupled from a shared model), thick (embeds its own model — XMLA-editing that model permanently blocks future .pbix download), or paginated, plus whether it's downloadable as a .pbix (service-authored reports aren't). Use to pick which reports are safe to export for analysis.")]
    public static Task<string> ReportInventory(string? workspace = null, CancellationToken ct = default)
        => DaxterToolRuntime.RestAsync(workspace, null, async (rest, cfg, c) =>
            await rest.ReportInventoryAsync(await rest.ResolveGroupIdAsync(cfg.Workspace, c), c), ct);

    [McpServerTool(Name = "daxter_export_report", ReadOnly = true, Title = "Export a report (definition + .pbix)"), Description("Download a report's artifacts: its PBIR/PBIR-Legacy definition (the JSON carrying every field reference — Table[Column], measures — for column-usage analysis) and/or its .pbix. By DEFAULT both are downloaded. Files are written under the persistent token volume (~/.daxter/exports/<report>/) and the tool returns where they landed; pass 'output_dir' to write elsewhere (mount a host path in the MCP config to land them on your machine). Pass pbix=false for just the definition, or definition=false for just the .pbix. Pass 'part' (e.g. report.json) to also return that definition file's content inline for analysis. .pbix fails for service-authored / XMLA-edited reports — that's reported, the definition still comes through. Reads only.")]
    public static Task<string> ExportReport(
        [Description("Report name or id.")] string report,
        [Description("Download the .pbix binary (default true).")] bool pbix = true,
        [Description("Download the PBIR/legacy definition JSON (default true).")] bool definition = true,
        [Description("Directory to write into (default: ~/.daxter/exports, which persists in the token volume).")] string? output_dir = null,
        [Description("Also return this definition file's content inline (e.g. report.json) for analysis.")] string? part = null,
        string? workspace = null, CancellationToken ct = default)
        => DaxterToolRuntime.RestTextAsync(workspace, async (rest, cfg, c) =>
        {
            var g = await rest.ResolveGroupIdAsync(cfg.Workspace, c);
            var rid = await rest.ResolveReportIdAsync(g, report, c);
            var dir = string.IsNullOrWhiteSpace(output_dir)
                ? Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.UserProfile), ".daxter", "exports")
                : output_dir;
            var safe = string.Concat(report.Select(ch => Path.GetInvalidFileNameChars().Contains(ch) ? '_' : ch));
            var log = new StringBuilder();
            string? inline = null;

            if (definition || !string.IsNullOrWhiteSpace(part))
            {
                var parts = await rest.ReportDefinitionAsync(g, rid, c);
                if (!string.IsNullOrWhiteSpace(part))
                {
                    var p = parts.FirstOrDefault(x => string.Equals(x.Path, part, StringComparison.OrdinalIgnoreCase));
                    inline = p?.Content ?? $"(part not found: {part}; available: {string.Join(", ", parts.Select(x => x.Path))})";
                }
                if (definition)
                {
                    var baseDir = Path.Combine(dir, safe);
                    foreach (var p in parts)
                    {
                        var dest = Path.Combine(baseDir, p.Path.Replace('/', Path.DirectorySeparatorChar));
                        Directory.CreateDirectory(Path.GetDirectoryName(dest)!);
                        await File.WriteAllTextAsync(dest, p.Content, c);
                    }
                    log.AppendLine($"definition: {parts.Count} part(s) → {baseDir}");
                }
            }
            if (pbix)
            {
                try
                {
                    var bytes = await rest.ExportReportPbixAsync(g, rid, c);
                    Directory.CreateDirectory(dir);
                    var pbixPath = Path.Combine(dir, safe + ".pbix");
                    await File.WriteAllBytesAsync(pbixPath, bytes, c);
                    log.AppendLine($"pbix: {bytes.Length:N0} bytes → {pbixPath}");
                }
                catch (Exception ex)
                {
                    log.AppendLine($"pbix: NOT downloaded — {ex.Message} (service-authored or XMLA-edited reports can't be exported as .pbix).");
                }
            }
            if (inline is not null) { log.AppendLine().AppendLine($"--- {part} ---").AppendLine(inline); }
            return log.Length == 0 ? "Nothing requested — set definition=true and/or pbix=true." : log.ToString();
        }, ct);

    [McpServerTool(Name = "daxter_item_connections", ReadOnly = true, Title = "List a model's connections"), Description("A model's current connections via the Fabric API: display name + connectivity type (cloud / on-prem / VNet gateway) + connection details. Works with model read/write (no gateway-admin), so it names bindings to gateways you can't manage.")]
    public static Task<string> ItemConnections(string? workspace = null, string? dataset = null, CancellationToken ct = default)
        => DaxterToolRuntime.RestAsync(workspace, dataset, async (rest, cfg, c) =>
        {
            var g = await rest.ResolveGroupIdAsync(cfg.Workspace, c);
            var d = await rest.ResolveDatasetIdAsync(g, cfg.Dataset!, c);
            return await rest.ItemConnectionsAsync(g, d, c);
        }, ct);

    [McpServerTool(Name = "daxter_discover_gateways", ReadOnly = true, Title = "Discover bindable gateways"), Description("List the gateways a model can be bound to (those with matching data sources), via REST.")]
    public static Task<string> DiscoverGateways(string? workspace = null, string? dataset = null, CancellationToken ct = default)
        => DaxterToolRuntime.RestAsync(workspace, dataset, async (rest, cfg, c) =>
        {
            var g = await rest.ResolveGroupIdAsync(cfg.Workspace, c);
            var d = await rest.ResolveDatasetIdAsync(g, cfg.Dataset!, c);
            return await rest.DiscoverGatewaysAsync(g, d, c);
        }, ct);

    [McpServerTool(Name = "daxter_gateway_datasources", ReadOnly = true, Title = "List a gateway's data sources"), Description("List the data sources (connections) on a gateway; their ids are what daxter_bind_to_gateway maps to.")]
    public static Task<string> GatewayDatasources(
        [Description("Gateway id (GUID) — from daxter_discover_gateways.")] string gatewayId, CancellationToken ct = default)
        => DaxterToolRuntime.RestTenantAsync((rest, c) => rest.GatewayDatasourcesAsync(gatewayId, c), ct);

    [McpServerTool(Name = "daxter_take_over", Destructive = true, Title = "Take over a model"), Description(
        "Take over ownership of a semantic model (the 'owner left' flow) — required before rebinding its gateway or credentials. " +
        "DRY-RUN by default; set execute=true AND enable writes (web console Configure → Allow writes, or DAXTER_MCP_ALLOW_WRITES=true) to apply. " +
        "Refused on PROD targets when DAXTER_MCP_BLOCK_PROD_WRITES=true.")]
    public static Task<string> TakeOver(
        [Description("Actually take over (default false = dry run).")] bool execute = false,
        string? workspace = null, string? dataset = null, CancellationToken ct = default)
        => DaxterToolRuntime.TakeOverAsync(workspace, dataset, execute, ct);

    [McpServerTool(Name = "daxter_bind_connection", Destructive = true, Title = "Bind a data source to a connection"), Description(
        "Bind a SINGLE semantic-model data source to a connection (Fabric Bind Semantic Model Connection API). Supports ALL " +
        "connectivity types: ShareableCloud (the cloud 'Maps to'), OnPremisesGateway, VirtualNetworkGateway, PersonalCloud, " +
        "Automatic (default SSO), or None (unbind). This SUPERSEDES daxter_bind_to_gateway — it's per-source and can set cloud " +
        "mappings the gateway API can't. Identify the source by its type + path (from daxter_item_connections); pass the target " +
        "connection's id (from daxter_connections) for ShareableCloud/gateway types, or omit it for Automatic/None. You must OWN " +
        "the model (daxter_take_over first). DRY-RUN unless execute=true AND writes enabled. PROD-blockable.")]
    public static Task<string> BindConnection(
        [Description("Data source type, e.g. SQL | Snowflake | Web (the 'type' from daxter_item_connections).")] string sourceType,
        [Description("Data source path identifying WHICH source, e.g. 'server;database' (the 'path' from daxter_item_connections).")] string sourcePath,
        [Description("Connectivity type: ShareableCloud | OnPremisesGateway | VirtualNetworkGateway | PersonalCloud | Automatic | None.")] string connectivityType,
        [Description("Target connection id (GUID) — from daxter_connections. Required for ShareableCloud/gateway; omit for Automatic/None.")] string? connectionId = null,
        [Description("Actually apply (default false = dry run).")] bool execute = false,
        string? workspace = null, string? dataset = null, CancellationToken ct = default)
        => DaxterToolRuntime.BindConnectionAsync(workspace, dataset, connectionId, connectivityType, sourceType, sourcePath, execute, ct);

    [McpServerTool(Name = "daxter_bind_to_gateway", Destructive = true, Title = "Bind a model to a gateway"), Description(
        "Bind a whole semantic model to ONE gateway (legacy Power BI BindToGateway), optionally mapping its sources to specific " +
        "gateway connection ids (comma-separated 'datasourceIds'; omit to bind the first matching data source per source). " +
        "Supports on-premises and VNet gateways. PREFER daxter_bind_connection — it's per-source and also does cloud 'Maps to'. " +
        "DRY-RUN by default; set execute=true AND enable writes to apply. PROD-blockable.")]
    public static Task<string> BindToGateway(
        [Description("Gateway id (GUID) to bind to — from daxter_discover_gateways.")] string gatewayId,
        [Description("Comma-separated gateway data-source/connection ids to map (optional; from daxter_gateway_datasources).")] string? datasourceIds = null,
        [Description("Actually bind (default false = dry run).")] bool execute = false,
        string? workspace = null, string? dataset = null, CancellationToken ct = default)
    {
        var ids = string.IsNullOrWhiteSpace(datasourceIds)
            ? null
            : datasourceIds.Split(',', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries);
        return DaxterToolRuntime.BindToGatewayAsync(workspace, dataset, gatewayId, ids, execute, ct);
    }

    [McpServerTool(Name = "daxter_lineage", ReadOnly = true, Title = "Report to dataset lineage"), Description("Report → dataset lineage for a workspace.")]
    public static Task<string> Lineage(string? workspace = null, CancellationToken ct = default)
        => DaxterToolRuntime.RestAsync(workspace, null, async (rest, cfg, c) =>
            await rest.LineageAsync(await rest.ResolveGroupIdAsync(cfg.Workspace, c), c), ct);

    [McpServerTool(Name = "daxter_export", ReadOnly = true, Title = "Export model (.bim)"), Description("Export the model's full definition as Tabular (.bim) JSON. Large output is truncated — use the CLI for the complete file.")]
    public static Task<string> Export(string? workspace = null, string? dataset = null, CancellationToken ct = default)
        => DaxterToolRuntime.ExportAsync(workspace, dataset, ct);

    [McpServerTool(Name = "daxter_permissions", ReadOnly = true, Title = "List permissions"), Description("Who has access. With a dataset → dataset users; without a dataset → workspace users.")]
    public static Task<string> Permissions(string? dataset = null, string? workspace = null, CancellationToken ct = default)
        => DaxterToolRuntime.RestAsync(workspace, dataset, async (rest, cfg, c) =>
        {
            var groupId = await rest.ResolveGroupIdAsync(cfg.Workspace, c);
            if (!string.IsNullOrWhiteSpace(cfg.Dataset))
            {
                var datasetId = await rest.ResolveDatasetIdAsync(groupId, cfg.Dataset!, c);
                return await rest.DatasetUsersAsync(groupId, datasetId, c);
            }

            return await rest.WorkspaceUsersAsync(groupId, c);
        }, ct);

    [McpServerTool(Name = "daxter_gateways", ReadOnly = true, Title = "List gateways"), Description("List gateways visible to the identity (requires gateway-admin rights).")]
    public static Task<string> Gateways(CancellationToken ct = default)
        => DaxterToolRuntime.RestTenantAsync((rest, c) => rest.GatewaysAsync(c), ct);

    [McpServerTool(Name = "daxter_datasources", ReadOnly = true, Title = "List data sources"), Description("Data sources and gateway binding used by a dataset's refresh.")]
    public static Task<string> Datasources(string? dataset = null, string? workspace = null, CancellationToken ct = default)
        => DaxterToolRuntime.RestAsync(workspace, dataset, async (rest, cfg, c) =>
        {
            var groupId = await rest.ResolveGroupIdAsync(cfg.Workspace, c);
            var datasetId = await rest.ResolveDatasetIdAsync(
                groupId, cfg.Dataset ?? throw new DaxterException("A dataset is required."), c);
            return await rest.DatasourcesAsync(groupId, datasetId, c);
        }, ct);

    [McpServerTool(Name = "daxter_test_rls", ReadOnly = true, Title = "Test RLS"), Description("Test RLS: run a DAX query impersonating a user and/or under a role; returns the filtered result.")]
    public static Task<string> TestRls(
        [Description("DAX query to evaluate under the identity, e.g. EVALUATE ROW(\"n\", COUNTROWS('Sales'))")] string query,
        [Description("RLS role name.")] string? role = null,
        [Description("User UPN to impersonate, e.g. user@contoso.com")] string? user = null,
        string? workspace = null, string? dataset = null, CancellationToken ct = default)
        => DaxterToolRuntime.TestRlsAsync(workspace, dataset, role, user, query, ct);

    [McpServerTool(Name = "daxter_pipelines", ReadOnly = true, Title = "List pipelines"), Description("List Fabric / Power BI deployment pipelines.")]
    public static Task<string> Pipelines(CancellationToken ct = default)
        => DaxterToolRuntime.RestTenantAsync((rest, c) => rest.PipelinesAsync(c), ct);

    [McpServerTool(Name = "daxter_pipeline_stages", ReadOnly = true, Title = "Pipeline stages"), Description("A deployment pipeline's stages (dev/test/prod) and their workspaces.")]
    public static Task<string> PipelineStages(
        [Description("Pipeline id (from daxter_pipelines).")] string pipelineId, CancellationToken ct = default)
        => DaxterToolRuntime.RestTenantAsync((rest, c) => rest.PipelineStagesAsync(pipelineId, c), ct);

    [McpServerTool(Name = "daxter_pipeline_operations", ReadOnly = true, Title = "Pipeline operations"), Description("Recent deploy operations for a pipeline.")]
    public static Task<string> PipelineOperations(
        [Description("Pipeline id (from daxter_pipelines).")] string pipelineId, CancellationToken ct = default)
        => DaxterToolRuntime.RestTenantAsync((rest, c) => rest.PipelineOperationsAsync(pipelineId, c), ct);

    [McpServerTool(Name = "daxter_pipeline_rules", ReadOnly = true, Title = "Pipeline deployment rules"), Description(
        "Deployment-rule check: a model's parameter values across each pipeline stage, flagging where they differ. " +
        "The public Power BI REST API can't read deployment rules directly, so DAXter reads the model's parameters in " +
        "each stage's workspace over XMLA and treats a per-stage value difference as a deployment rule (or manual override). " +
        "Returns columns: Parameter, <stage workspaces…>, RuleApplied.")]
    public static Task<string> PipelineRules(
        [Description("Pipeline id (from daxter_pipelines).")] string pipelineId,
        [Description("Model (semantic dataset) name — same in every stage.")] string model,
        CancellationToken ct = default)
        => DaxterToolRuntime.PipelineRulesAsync(pipelineId, model, ct);

    [McpServerTool(Name = "daxter_pipeline_models_without_rules", ReadOnly = true, Title = "Models without rules"), Description(
        "Pipeline-wide audit: lists models in a pipeline whose parameter values are identical across every stage " +
        "— i.e. no deployment rule (and no manual override) is in effect. Scans every model's parameters in every " +
        "stage via XMLA; potentially slow on large pipelines.")]
    public static Task<string> PipelineModelsWithoutRules(
        [Description("Pipeline id (from daxter_pipelines).")] string pipelineId,
        CancellationToken ct = default)
        => DaxterToolRuntime.PipelineModelsWithoutRulesAsync(pipelineId, ct);

    [McpServerTool(Name = "daxter_pipeline_param_check", ReadOnly = true, Title = "Pipeline parameter check"), Description(
        "Pipeline-wide audit: lists every model whose <param> in <stage> equals (or, with notEquals=true, does not equal) " +
        "<value>. Useful for verifying a deployment rule is consistently applied across all models in an environment " +
        "(e.g. WAREHOUSE_URL in 'Prod' = a fixed endpoint). Scans every model's parameters in every stage via XMLA.")]
    public static Task<string> PipelineParamCheck(
        [Description("Pipeline id (from daxter_pipelines).")] string pipelineId,
        [Description("Stage workspace name (e.g. 'Prod').")] string stage,
        [Description("Parameter name (e.g. DATABASE_NAME).")] string param,
        [Description("Expected value to match against.")] string value,
        [Description("When true, find models whose value does NOT equal the expected.")] bool notEquals = false,
        [Description("Optional: a single model (e.g. 'Sales') — checks just that model and reports its actual value + pass/fail. Omit to scan all models.")] string? model = null,
        CancellationToken ct = default)
        => DaxterToolRuntime.PipelineParamCheckAsync(pipelineId, stage, param, value, notEquals, model, ct);

    [McpServerTool(Name = "daxter_audit_list_saved", ReadOnly = true, Title = "List saved audit checks"), Description(
        "List the named audit checks saved from the web console (shared via ~/.daxter). " +
        "Columns: Name, Pipeline, Stage, Param, Expected. Run one with daxter_audit_run_saved.")]
    public static Task<string> AuditListSaved(CancellationToken ct = default)
        => DaxterToolRuntime.AuditListSavedAsync(ct);

    [McpServerTool(Name = "daxter_audit_run_saved", ReadOnly = true, Title = "Run saved audit check"), Description(
        "Run a saved audit check by its name (as shown by daxter_audit_list_saved) — re-runs the " +
        "stored parameter-value check against its pipeline and returns the matching models.")]
    public static Task<string> AuditRunSaved(
        [Description("Saved check name (case-insensitive).")] string name,
        CancellationToken ct = default)
        => DaxterToolRuntime.AuditRunSavedAsync(name, ct);

    [McpServerTool(Name = "daxter_audit_run_all_saved", ReadOnly = true, Title = "Run all saved audit checks"), Description(
        "Run every saved rule for a pipeline against a fresh scan and list, per rule, the models that match its condition. " +
        "Columns: Rule, Param, Stage, Expected, Matches (matched/checked).")]
    public static Task<string> AuditRunAllSaved(
        [Description("Pipeline id (from daxter_pipelines).")] string pipelineId,
        [Description("Optional: a single model (e.g. 'Sales') — evaluate every saved rule against just that model. Omit for all models.")] string? model = null,
        CancellationToken ct = default)
        => DaxterToolRuntime.AuditRunAllSavedAsync(pipelineId, model, ct);

    // ---- Gated write tools (DRY-RUN by default; enable writes via the web console toggle or DAXTER_MCP_ALLOW_WRITES) ----

    [McpServerTool(Name = "daxter_refresh", Destructive = true, Title = "Refresh model / table / partition"), Description(
        "Refresh a model/table/partition(s). DRY-RUN by default (returns the plan without queueing). " +
        "To run, set execute=true AND enable writes (web console Configure → Allow writes, or DAXTER_MCP_ALLOW_WRITES=true). " +
        "Refreshes are QUEUED onto a shared queue and run by the single worker (the web container), serialized one refresh per " +
        "model (different models run in parallel); this returns a job id — track it with daxter_refresh_jobs. " +
        "If a partition refresh FAILS or is INTERRUPTED, you do NOT need to start over: call " +
        "daxter_resume_refresh(job_id) to pick up where it left off — it re-runs only the not-yet-done partitions. " +
        "(daxter_refresh_jobs also returns a ready-to-use resume_hint for each failed/interrupted job.) " +
        "PROD targets are allowed by default; set DAXTER_MCP_BLOCK_PROD_WRITES=true to re-block them. " +
        "scope=partition refreshes ONE partition; scope=partitions refreshes all of a table's partitions (or the subset in 'partitions'), in order.")]
    public static Task<string> Refresh(
        [Description("Scope: model | table | partition | partitions")] string scope = "model",
        [Description("Table name (required for table/partition/partitions).")] string? table = null,
        [Description("Partition name (required for scope=partition).")] string? partition = null,
        [Description("Comma-separated partition names for scope=partitions (a subset). Omit to refresh ALL partitions of the table.")] string? partitions = null,
        [Description("Refresh type: full|automatic|calculate|dataOnly|clearValues")] string? type = null,
        [Description("Partition order for scope=partitions: newest-first | oldest-first")] string? order = null,
        [Description("Actually queue it (default false = dry run).")] bool execute = false,
        [Description("Retry the refresh up to N times on transient failure (default 0; e.g. 3). Linear backoff.")] int retries = 0,
        string? workspace = null, string? dataset = null, CancellationToken ct = default)
    {
        var s = scope.Trim().ToLowerInvariant();
        var rtype = MaintenanceService.ParseRefreshType(type);

        var (kind, parts) = s switch
        {
            "model" => (RefreshKind.Model, (IReadOnlyList<string>?)null),
            "table" => (RefreshKind.Table, null),
            "partition" => (RefreshKind.Partition, null),
            "partitions" => string.IsNullOrWhiteSpace(partitions)
                ? (RefreshKind.AllPartitions, null)
                : (RefreshKind.SomePartitions,
                    partitions.Split(',', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries)),
            _ => throw new DaxterException($"Unknown scope '{scope}'. Use model | table | partition | partitions."),
        };

        if (kind is RefreshKind.Table or RefreshKind.Partition or RefreshKind.AllPartitions or RefreshKind.SomePartitions
            && string.IsNullOrWhiteSpace(table))
            throw new DaxterException($"table is required for scope={s}.");
        if (kind == RefreshKind.Partition && string.IsNullOrWhiteSpace(partition))
            throw new DaxterException("partition is required for scope=partition.");

        return DaxterToolRuntime.EnqueueRefreshAsync(
            workspace, dataset, kind, table, partition,
            DaxterToolRuntime.ParseOrder(order), rtype, parts, execute, retries, ct);
    }

    [McpServerTool(Name = "daxter_resume_refresh", Destructive = true, Title = "Resume a refresh job"), Description(
        "Re-run a finished/interrupted/failed refresh job by id (from daxter_refresh_jobs). By DEFAULT resumes " +
        "only the NOT-yet-done partitions (a partition job that recorded its order + progress) — so a 68-partition " +
        "job interrupted at 24 re-runs just the remaining 44 (the failed/in-flight one included). Pass " +
        "remaining_only=false for a full re-run. DRY-RUN unless execute=true AND writes are enabled; queues onto the " +
        "shared worker.")]
    public static Task<string> ResumeRefresh(
        [Description("Job id to resume (from daxter_refresh_jobs).")] int job_id,
        [Description("Resume only the not-yet-done partitions (default true). false = full re-run.")] bool remaining_only = true,
        [Description("Actually queue it (default false = dry run).")] bool execute = false,
        CancellationToken ct = default)
        => DaxterToolRuntime.ResumeRefreshAsync(job_id, remaining_only, execute, ct);

    [McpServerTool(Name = "daxter_refresh_jobs", ReadOnly = true, Title = "List refresh jobs"), Description(
        "List refresh jobs on the shared queue (queued/running/finished) — across ALL interfaces (CLI, MCP, web). " +
        "Pass workspace+dataset to filter to one model. Shows whether a worker is currently running to drain the queue. " +
        "Each FAILED/INTERRUPTED job carries a 'resume_hint' — the exact daxter_resume_refresh call to recover it, " +
        "re-running only the not-yet-done partitions. Use it to self-recover failed refreshes without starting over.")]
    public static string RefreshJobs(
        [Description("Filter to one model's workspace (optional; needs dataset too).")] string? workspace = null,
        [Description("Filter to one model's dataset (optional; needs workspace too).")] string? dataset = null,
        [Description("Most recent N jobs (default 20).")] int top = 20)
        => DaxterToolRuntime.RefreshJobsJson(workspace, dataset, top);

    [McpServerTool(Name = "daxter_clear_cache", Destructive = true, Title = "Clear data cache"), Description(
        "Clear the model's data cache. DRY-RUN by default; requires execute=true AND writes enabled " +
        "(web console Configure → Allow writes, or DAXTER_MCP_ALLOW_WRITES=true).")]
    public static Task<string> ClearCache(
        [Description("Actually execute (default false = dry run).")] bool execute = false,
        [Description("Retry up to N times on transient failure (default 0).")] int retries = 0,
        string? workspace = null, string? dataset = null, CancellationToken ct = default)
        => DaxterToolRuntime.MaintenanceAsync(workspace, dataset, svc => svc.BuildClearCache(), execute, ct, retries);

    // ---- Gated MODEL-EDIT tools (DRY-RUN by default; require execute=true AND model edits enabled —
    //      web console "Allow model edits" or DAXTER_MCP_ALLOW_MODEL_EDIT=true. IRREVERSIBLE for PBIX
    //      download; a .bim backup is written before every apply.) ----

    private const string EditNote =
        " DRY-RUN by default (previews the change; raw TMSL shows the TMSL). To apply, set execute=true AND enable model edits " +
        "(web console Configure → Allow model edits, or DAXTER_MCP_ALLOW_MODEL_EDIT=true). Editing a " +
        "Power BI Desktop model over XMLA is IRREVERSIBLE for PBIX download; a .bim backup is taken first.";

    [McpServerTool(Name = "daxter_edit_measure", Destructive = true, Title = "Create / alter measure"),
     Description("Create or alter a measure (DAX) on a table." + EditNote)]
    public static Task<string> EditMeasure(
        [Description("Table that owns the measure.")] string table,
        [Description("Measure name.")] string name,
        [Description("DAX expression.")] string dax,
        [Description("Format string, e.g. $#,0.00 (optional).")] string? formatString = null,
        [Description("Display folder (optional).")] string? displayFolder = null,
        [Description("Description (optional).")] string? description = null,
        [Description("Actually apply (default false = dry run).")] bool execute = false,
        string? workspace = null, string? dataset = null, CancellationToken ct = default)
        => DaxterToolRuntime.ModelEditAsync(workspace, dataset,
            svc => svc.UpsertMeasure(table, name, dax, formatString, displayFolder, description), execute, ct);

    [McpServerTool(Name = "daxter_delete_measure", Destructive = true, Title = "Delete measure"),
     Description("Delete a measure from a table." + EditNote)]
    public static Task<string> DeleteMeasure(
        [Description("Table that owns the measure.")] string table,
        [Description("Measure name.")] string name,
        [Description("Actually apply (default false = dry run).")] bool execute = false,
        string? workspace = null, string? dataset = null, CancellationToken ct = default)
        => DaxterToolRuntime.ModelEditAsync(workspace, dataset, svc => svc.DeleteMeasure(table, name), execute, ct);

    [McpServerTool(Name = "daxter_set_parameter", Destructive = true, Title = "Set parameter / M expression"),
     Description("Create or alter a shared M expression / parameter (model-level)." + EditNote)]
    public static Task<string> SetParameter(
        [Description("Parameter / expression name.")] string name,
        [Description("The M expression (Power Query).")] string mExpression,
        [Description("Description (optional).")] string? description = null,
        [Description("Actually apply (default false = dry run).")] bool execute = false,
        string? workspace = null, string? dataset = null, CancellationToken ct = default)
        => DaxterToolRuntime.ModelEditAsync(workspace, dataset,
            svc => svc.UpsertExpression(name, mExpression, description), execute, ct);

    [McpServerTool(Name = "daxter_delete_parameter", Destructive = true, Title = "Delete parameter / M expression"),
     Description("Delete a shared M expression / parameter." + EditNote)]
    public static Task<string> DeleteParameter(
        [Description("Parameter / expression name.")] string name,
        [Description("Actually apply (default false = dry run).")] bool execute = false,
        string? workspace = null, string? dataset = null, CancellationToken ct = default)
        => DaxterToolRuntime.ModelEditAsync(workspace, dataset, svc => svc.DeleteExpression(name), execute, ct);

    [McpServerTool(Name = "daxter_edit_role", Destructive = true, Title = "Create / alter RLS role"),
     Description("Create or alter a security (RLS/OLS) role with members and an optional table filter." + EditNote)]
    public static Task<string> EditRole(
        [Description("Role name.")] string name,
        [Description("Model permission: read | readRefresh | refresh | administrator | none (default read).")] string? modelPermission = null,
        [Description("Comma-separated member UPNs / group names (optional).")] string? members = null,
        [Description("Table to apply an RLS filter to (optional).")] string? filterTable = null,
        [Description("DAX filter expression for filterTable, e.g. [Region] = \"US\" (optional).")] string? filterDax = null,
        [Description("Actually apply (default false = dry run).")] bool execute = false,
        string? workspace = null, string? dataset = null, CancellationToken ct = default)
        => DaxterToolRuntime.ModelEditAsync(workspace, dataset, svc => svc.UpsertRole(
            name, modelPermission,
            (members ?? "").Split(',', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries).Select(m => new RoleMember(m)),
            string.IsNullOrWhiteSpace(filterTable) ? null : [new TableFilter(filterTable, filterDax ?? "")]), execute, ct);

    [McpServerTool(Name = "daxter_delete_role", Destructive = true, Title = "Delete RLS role"),
     Description("Delete a security role." + EditNote)]
    public static Task<string> DeleteRole(
        [Description("Role name.")] string name,
        [Description("Actually apply (default false = dry run).")] bool execute = false,
        string? workspace = null, string? dataset = null, CancellationToken ct = default)
        => DaxterToolRuntime.ModelEditAsync(workspace, dataset, svc => svc.DeleteRole(name), execute, ct);

    [McpServerTool(Name = "daxter_edit_calculated_column", Destructive = true, Title = "Create / alter calculated column"),
     Description("Create or alter a calculated column (DAX) on a table." + EditNote)]
    public static Task<string> EditCalculatedColumn(
        [Description("Table that owns the column.")] string table,
        [Description("Column name.")] string name,
        [Description("DAX expression.")] string dax,
        [Description("Data type: string | int64 | double | decimal | dateTime | boolean (optional; inferred if omitted).")] string? dataType = null,
        [Description("Actually apply (default false = dry run).")] bool execute = false,
        string? workspace = null, string? dataset = null, CancellationToken ct = default)
        => DaxterToolRuntime.ModelEditAsync(workspace, dataset,
            svc => svc.UpsertCalculatedColumn(table, name, dax, dataType), execute, ct);

    [McpServerTool(Name = "daxter_edit_column", Destructive = true, Title = "Edit column properties"),
     Description("Edit an EXISTING column's presentation/metadata on any column (data or calculated) — format string, " +
                "data type, sort-by column, summarize-by, display folder, description, hidden, data category — via TOM " +
                "(no DAX needed). This is the path Tabular Editor/Desktop use; raw TMSL can't edit a standalone column. " +
                "Only the properties you pass change (omit to leave as-is; empty string clears a text property)." + EditNote)]
    public static Task<string> EditColumn(
        [Description("Table that owns the column.")] string table,
        [Description("Column name.")] string name,
        [Description("Format string, e.g. \"#,0\" or \"$#,0.00\" or \"0.0%\" (optional).")] string? formatString = null,
        [Description("Data type: string | int64 | double | decimal | dateTime | boolean (optional).")] string? dataType = null,
        [Description("Name of another column on the same table to sort this column by (optional; empty string clears it).")] string? sortByColumn = null,
        [Description("Default summarization: none | sum | average | min | max | count | distinctCount (optional).")] string? summarizeBy = null,
        [Description("Display folder (optional).")] string? displayFolder = null,
        [Description("Description (optional).")] string? description = null,
        [Description("Hide the column from report view (optional).")] bool? isHidden = null,
        [Description("Data category, e.g. Years | Months | Place | WebUrl (optional).")] string? dataCategory = null,
        [Description("Actually apply (default false = dry run).")] bool execute = false,
        string? workspace = null, string? dataset = null, CancellationToken ct = default)
        => DaxterToolRuntime.ModelEditAsync(workspace, dataset,
            svc => svc.EditColumn(table, name, formatString, dataType, sortByColumn, summarizeBy,
                displayFolder, description, isHidden, dataCategory), execute, ct);

    [McpServerTool(Name = "daxter_delete_column", Destructive = true, Title = "Delete column"),
     Description("Delete a column from a table." + EditNote)]
    public static Task<string> DeleteColumn(
        [Description("Table that owns the column.")] string table,
        [Description("Column name.")] string name,
        [Description("Actually apply (default false = dry run).")] bool execute = false,
        string? workspace = null, string? dataset = null, CancellationToken ct = default)
        => DaxterToolRuntime.ModelEditAsync(workspace, dataset, svc => svc.DeleteColumn(table, name), execute, ct);

    [McpServerTool(Name = "daxter_set_partition_source", Destructive = true, Title = "Set partition (M) source"),
     Description("Set a partition's Power Query (M) source expression." + EditNote)]
    public static Task<string> SetPartitionSource(
        [Description("Table that owns the partition.")] string table,
        [Description("Partition name.")] string partition,
        [Description("The M (Power Query) expression for the partition source.")] string mExpression,
        [Description("Actually apply (default false = dry run).")] bool execute = false,
        string? workspace = null, string? dataset = null, CancellationToken ct = default)
        => DaxterToolRuntime.ModelEditAsync(workspace, dataset,
            svc => svc.SetPartitionSource(table, partition, mExpression), execute, ct);

    [McpServerTool(Name = "daxter_create_calculated_table", Destructive = true, Title = "Create calculated table"),
     Description("Create or replace a calculated table (a table whose partition is a DAX expression)." + EditNote)]
    public static Task<string> CreateCalculatedTable(
        [Description("Table name.")] string name,
        [Description("DAX table expression, e.g. CALENDARAUTO().")] string dax,
        [Description("Actually apply (default false = dry run).")] bool execute = false,
        string? workspace = null, string? dataset = null, CancellationToken ct = default)
        => DaxterToolRuntime.ModelEditAsync(workspace, dataset, svc => svc.CreateCalculatedTable(name, dax), execute, ct);

    [McpServerTool(Name = "daxter_delete_table", Destructive = true, Title = "Delete table"),
     Description("Delete an entire table (and its children)." + EditNote)]
    public static Task<string> DeleteTable(
        [Description("Table name.")] string name,
        [Description("Actually apply (default false = dry run).")] bool execute = false,
        string? workspace = null, string? dataset = null, CancellationToken ct = default)
        => DaxterToolRuntime.ModelEditAsync(workspace, dataset, svc => svc.DeleteTable(name), execute, ct);

    [McpServerTool(Name = "daxter_create_import_table", Destructive = true, Title = "Create import table"),
     Description("Create or replace an import table: an M (Power Query) source + typed columns mapped to the M output." + EditNote)]
    public static Task<string> CreateImportTable(
        [Description("Table name.")] string name,
        [Description("The M (Power Query) expression for the partition source.")] string mExpression,
        [Description("Columns as 'Name:dataType:sourceColumn', comma-separated (dataType: string|int64|double|decimal|dateTime|boolean).")] string columns,
        [Description("Actually apply (default false = dry run).")] bool execute = false,
        string? workspace = null, string? dataset = null, CancellationToken ct = default)
        => DaxterToolRuntime.ModelEditAsync(workspace, dataset,
            svc => svc.CreateImportTable(name, mExpression, ParseColumnSpecs(columns)), execute, ct);

    [McpServerTool(Name = "daxter_edit_relationship", Destructive = true, Title = "Create / alter relationship"),
     Description("Create or alter a single-column relationship fromTable[fromColumn] → toTable[toColumn] (many-to-one)." + EditNote)]
    public static Task<string> EditRelationship(
        [Description("'From' (many-side) table.")] string fromTable,
        [Description("'From' column.")] string fromColumn,
        [Description("'To' (one-side) table.")] string toTable,
        [Description("'To' column.")] string toColumn,
        [Description("Relationship name (optional; auto-derived if omitted).")] string? name = null,
        [Description("Cross-filter: single | both | automatic (default single).")] string? crossFilter = null,
        [Description("Whether the relationship is active (default true).")] bool isActive = true,
        [Description("Actually apply (default false = dry run).")] bool execute = false,
        string? workspace = null, string? dataset = null, CancellationToken ct = default)
        => DaxterToolRuntime.ModelEditAsync(workspace, dataset,
            svc => svc.UpsertRelationship(fromTable, fromColumn, toTable, toColumn, name, crossFilter, isActive), execute, ct);

    [McpServerTool(Name = "daxter_delete_relationship", Destructive = true, Title = "Delete relationship"),
     Description("Delete a relationship by name." + EditNote)]
    public static Task<string> DeleteRelationship(
        [Description("Relationship name.")] string name,
        [Description("Actually apply (default false = dry run).")] bool execute = false,
        string? workspace = null, string? dataset = null, CancellationToken ct = default)
        => DaxterToolRuntime.ModelEditAsync(workspace, dataset, svc => svc.DeleteRelationship(name), execute, ct);

    private static IEnumerable<SourceColumn> ParseColumnSpecs(string spec) =>
        (spec ?? "").Split(',', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries)
            .Select(part => part.Split(':', StringSplitOptions.TrimEntries))
            .Select(p => p.Length >= 3
                ? new SourceColumn(p[0], p[1], p[2])
                : throw new DaxterException($"Bad column spec '{string.Join(":", p)}'. Use Name:dataType:sourceColumn."));

    [McpServerTool(Name = "daxter_edit_tmsl", Destructive = true, Title = "Run raw TMSL edit"),
     Description("Execute a raw TMSL command (createOrReplace / alter / delete / …) — the escape hatch for " +
                 "edits not covered by the typed tools." + EditNote)]
    public static Task<string> EditTmsl(
        [Description("A TMSL command object, e.g. {\"createOrReplace\":{\"object\":{...},\"measure\":{...}}}.")] string tmsl,
        [Description("Actually apply (default false = dry run).")] bool execute = false,
        string? workspace = null, string? dataset = null, CancellationToken ct = default)
        => DaxterToolRuntime.ModelEditAsync(workspace, dataset, svc => svc.Raw(tmsl), execute, ct);

    // ---- Fabric SQL endpoints (Warehouse + Lakehouse SQL analytics endpoint) ----

    [McpServerTool(Name = "daxter_sql_endpoints", ReadOnly = true, Title = "List Fabric SQL endpoints"),
     Description("List every Fabric SQL endpoint in a workspace — each Warehouse and each Lakehouse's SQL analytics endpoint — " +
                 "with name, server (TDS hostname), database, and kind (Warehouse | Lakehouse). " +
                 "Call this FIRST to discover targets for daxter_sql_query; you pass the friendly name back, no GUID hostname required.")]
    public static Task<string> SqlEndpoints(
        [Description("Workspace name or id (optional; defaults to server config).")] string? workspace = null,
        CancellationToken ct = default)
        => DaxterToolRuntime.SqlEndpointsAsync(workspace, ct);

    [McpServerTool(Name = "daxter_sql_objects", ReadOnly = true, Title = "List SQL endpoint objects (schemas + tables/views/functions/procs)"),
     Description("List every schema and every Table / View / Function / Stored Procedure on a Fabric SQL endpoint, " +
                 "as (schema, kind, name) rows. One INFORMATION_SCHEMA round-trip; resolves the endpoint NAME (from " +
                 "daxter_sql_endpoints) into the server/database for you. " +
                 "Use this before daxter_sql_query to discover what's queryable — pick a table, then SELECT from it.")]
    public static Task<string> SqlObjects(
        [Description("Workspace name or id.")] string workspace,
        [Description("Warehouse or Lakehouse name (from daxter_sql_endpoints).")] string endpoint,
        CancellationToken ct = default)
        => DaxterToolRuntime.SqlObjectsAsync(workspace, endpoint, ct);

    [McpServerTool(Name = "daxter_sql_export", ReadOnly = true, Title = "Export full T-SQL result set as CSV (streaming)"),
     Description("Stream a Fabric SQL endpoint query's FULL result set as CSV to a file on DAXter's persistent volume " +
                 "(~/.daxter/exports/sql/). Use this instead of daxter_sql_query when you want every row — " +
                 "daxter_sql_query materializes the result set in memory and is meant for sampling; daxter_sql_export " +
                 "streams row-by-row straight to disk, so SELECT * on a multi-million-row table won't OOM. " +
                 "Returns the on-disk path and row count; tell the user to docker cp it off the container, or mount " +
                 "the daxter-tokens volume on a host path to get the file directly. Same writes-gate as daxter_sql_query. " +
                 "Pass quoteAll=true and/or crlf=true to match Power BI / Excel \"Export data\" style (quote every " +
                 "field, CRLF line endings) when the downstream consumer needs that exact format.")]
    public static Task<string> SqlExport(
        [Description("Workspace name or id.")] string workspace,
        [Description("Warehouse or Lakehouse name (from daxter_sql_endpoints).")] string endpoint,
        [Description("T-SQL statement (typically a SELECT).")] string sql,
        [Description("Wrap every field in quotes (Power BI / Excel \"Export data\" style). Default false = RFC 4180 quote-when-needed.")] bool quoteAll = false,
        [Description("End lines with CRLF (\\r\\n) instead of LF (\\n). Excel-on-Windows convention. Default false.")] bool crlf = false,
        CancellationToken ct = default)
        => DaxterToolRuntime.SqlExportAsync(workspace, endpoint, sql, ct, quoteAll, crlf);

    [McpServerTool(Name = "daxter_sql_query", ReadOnly = true, Title = "Run T-SQL on a Fabric SQL endpoint"),
     Description("Run T-SQL on a Fabric Warehouse or Lakehouse SQL endpoint. Pass the workspace and the endpoint NAME " +
                 "(from daxter_sql_endpoints) — the tool resolves the server + database for you. " +
                 "Authenticates with the same MSAL account daxter_login signs in (no separate sign-in for SQL). " +
                 "READ-ONLY by default — SELECT/EXPLAIN/SHOW/CTE-feeding-SELECT runs unconditionally. " +
                 "INSERT/UPDATE/DELETE/MERGE/DDL/EXEC is REFUSED unless the writes gate is on " +
                 "(Configure → Allow writes, or DAXTER_MCP_ALLOW_WRITES=true) AND the workspace doesn't look like PROD.")]
    public static Task<string> SqlQuery(
        [Description("Workspace name or id.")] string workspace,
        [Description("Warehouse or Lakehouse name (from daxter_sql_endpoints).")] string endpoint,
        [Description("T-SQL statement(s).")] string sql,
        CancellationToken ct = default)
        => DaxterToolRuntime.SqlQueryAsync(workspace, endpoint, sql, ct);
}
